### ISSUE TITLE
Elementor-Pro - FormModule - Checkboxes are not available as required fields

### ISSUE THREAD

**Issue by SoftwareManufakturDresden** [pojome/elementor#2134]
Hello elementor-pro Team,

currently it is not possible to create a form with checkboxes that are marked as required. We need such checkboxes that are mandatory fields.

I also checked the code of the form module and can provide you an solution, that works fine on my website.

File: elementor-pro/modules/forms/widgets/form.php
Line: 125
Description: Remove "checkbox" from 'value', to make checkboxes also available as required field.
**Old Code**
```
$repeater->add_control(
			'required',
			[
				'label' => __( 'Required', 'elementor-pro' ),
				'type' => Controls_Manager::SWITCHER,
				'label_on' => __( 'Yes', 'elementor-pro' ),
				'label_off' => __( 'No', 'elementor-pro' ),
				'return_value' => 'true',
				'default' => '',
				'conditions' => [
					'terms' => [
						[
							'name' => 'field_type',
							'operator' => '!in',
							'value' => [
                                                                'checkbox',
								'recaptcha',
							],
						],
					],
				],
			]
		);
```
**New Code**
```
$repeater->add_control(
			'required',
			[
				'label' => __( 'Required', 'elementor-pro' ),
				'type' => Controls_Manager::SWITCHER,
				'label_on' => __( 'Yes', 'elementor-pro' ),
				'label_off' => __( 'No', 'elementor-pro' ),
				'return_value' => 'true',
				'default' => '',
				'conditions' => [
					'terms' => [
						[
							'name' => 'field_type',
							'operator' => '!in',
							'value' => [
								'recaptcha',
							],
						],
					],
				],
			]
		);
```

Further more.
File: elementor-pro/modules/forms/classes/form-base.php
Line: 124
Description: Remove check for radio field, because checkbox can be also required fields.
**Old Code:**
```
$html .= '<span class="elementor-field-option"><input type="' . $type . '"
							value="' . esc_attr( $option ) . '"
							id="' . $this->get_attribute_id( $item_index ) . '-' . $key . '"
							name="' . $this->get_attribute_name( $item ) . ( ( 'checkbox' === $type && count( $options ) > 1 ) ? '[]"' : '"' ) .
							( ( $item['required'] && 'radio' === $type ) ? ' required aria-required="true"' : '' ) . '>
							<label for="' . $this->get_attribute_id( $item ) . '-' . $key . '">' . $option . '</label></span>';
```

**New Code:**
```
$html .= '<span class="elementor-field-option"><input type="' . $type . '"
							value="' . esc_attr( $option ) . '"
							id="' . $this->get_attribute_id( $item ) . '-' . $key . '"
							name="' . $this->get_attribute_name( $item ) . ( ( 'checkbox' === $type && count( $options ) > 1 ) ? '[]"' : '"' ) .
							( ( $item['required'] ) ? ' required aria-required="true"' : '' ) . '>
							<label for="' . $this->get_attribute_id( $item ) . '-' . $key . '">' . $option . '</label></span>';
```

Thanks in advance

**Comment by SoftwareManufakturDresden** [comment]
See also patch file.
[patch.diff.txt](https://github.com/pojome/elementor/files/1210801/patch.diff.txt)

**Comment by micha77dd** [comment]
We would like to update to latest Elementor-Pro version but this missing feature prevents simple 'one-click'-updates. Do you plan to integrate the attached patch into one of the next Elementor-Pro releases?

**Comment by bainternet** [comment]
I merged this issue with  #1693 , which are in the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Comment by ashkan-ahmadi** [comment]
apparently after 3 years, there have been no fixes yet!!!

**Comment by ashkan-ahmadi** [comment]
I just tried this. It worked like magic. Thank you so much. The line numbers won't match so use Find in Page to look for **'checkbox',** and **&& 'radio' === $type** and remove them.

In this case, all the checkbox options must be selected. Any idea how to limit to at least one?

**Comment by plethoradesign** [comment]
I was very surprised when I was unable to make a checkbox field required. Crazy that this is still not fixed in the current release.

**Comment by serialtasted** [comment]
> I was very surprised when I was unable to make a checkbox field required. Crazy that this is still not fixed in the current release.

It is possible. You have to use "Acceptance" field type instead

**Comment by benjaminadrom** [comment]
> > I was very surprised when I was unable to make a checkbox field required. Crazy that this is still not fixed in the current release.
> 
> It is possible. You have to use "Acceptance" field type instead

It's actually not very dynamic, what if you have multiple checkboxes and you have at least checked a single checkbox?
then this acceptance field is useless, sadly

**Comment by pepkolajk** [comment]
Still no solution?

**Comment by datatime-sk** [comment]
+1 This must be available. Please.

**Comment by vsapountzis** [comment]
+1

**Comment by vsapountzis** [comment]
For anyone looking for a simpler solution I was able to resolve it with jQuery like so: 

`function form_checkboxes_validation(){
?>
    <script type="text/javascript">
	(function($){
	   $("#submit").click(function(){
	    if(! $('input[name="form_fields[required_checkbox][]"]').is(':checked')) {
		alert("Please select at least one suite!");
		return false;
	    }
	});
	})(jQuery);
    </script>
<?php
}
add_action('wp_footer', 'form_checkboxes_validation');`

**Comment by themadhatmedia** [comment]
This is insane that this does not exist and has been talked about since 2017!
@vsapountzis i tried your code but did not work, any suggestions?
I put pasted this in Elementor-->custom code-->all pages

<script type="text/javascript">
(function($){
$("#submit").click(function(){
if(! $('input[name="form_fields[required_checkbox][]"]').is(':checked')) {
alert("Please select at least one suite!");
return false;
}
});
})(jQuery);
</script>

**Comment by vsapountzis** [comment]
@themadhatmedia Please use the following snippet inside your child theme functions file and let me know if it worked for you. Make sure to replace the "required_checkbox" name with the ID that you have set in the field of the form under advanced.

`
function form_checkboxes_validation(){
?>
	<script type="text/javascript">
		(function($){
			$("#send-request").click(function(){
				if(! $('input[name="form_fields[required_checkbox][]"]').is(':checked')) {
						alert("Please select at least one Suite!");
						return false;
				}
			});
		})(jQuery);
	</script>
<?php
}
add_action('wp_footer', 'form_checkboxes_validation');
`

**Comment by ok-ttc** [comment]
Is there any update on this? HTML 5 has a simple attribute called "required". I really would ned to set this from Elementor. Is there no news on this? This issue is open for many years now! What is the difficulty with this?

**Comment by caspervoogt** [comment]
> > I was very surprised when I was unable to make a checkbox field required. Crazy that this is still not fixed in the current release.
> 
> It is possible. You have to use "Acceptance" field type instead

That's OK for a single checkbox  but not for a multi-checkbox.

**Comment by caspervoogt** [comment]
> Is there any update on this? HTML 5 has a simple attribute called "required". I really would ned to set this from Elementor. Is there no news on this? This issue is open for many years now! What is the difficulty with this?

Every form element in Elementor should come with a required option.  The Elementor team must have forgotten this one,  because what reason could there possibly be to not add it to this one field type?!

**Comment by manig-metaweb** [comment]
> I just tried this. It worked like magic. Thank you so much. The line numbers won't match so use Find in Page to look for **'checkbox',** and **&& 'radio' === $type** and remove them.
> 
> In this case, all the checkbox options must be selected. Any idea how to limit to at least one?

Step : 1
elementor-pro\modules\forms\widgets\form.php

line 147
- function name " register_controls "
- hide the "checkbox"

$repeater->add_control(
		'required',
		[
			'label' => esc_html__( 'Required', 'elementor-pro' ),
			'type' => Controls_Manager::SWITCHER,
			'return_value' => 'true',
			'default' => '',
			'conditions' => [
				'terms' => [
					[
						'name' => 'field_type',
						'operator' => '!in',
						'value' => [
							// 'checkbox',
							'recaptcha',
							'recaptcha_v3',
							'hidden',
							'html',
							'step',
						],
					],
				],
			],
		]
	);
Step : 2
elementor-pro\modules\forms\classes
line 150
Replace the below function

protected function make_radio_checkbox_field( $item, $item_index, $type ) {
	$options = preg_split( "/\\r\\n|\\r|\\n/", $item['field_options'] );
	$html = '';
	if ( $options ) {

		
		$element_required = ($item['required'] && 'checkbox' === $type)?"element_required":"";
		$item_id = $item['custom_id'];
		$html .= '<div class="elementor-field-subgroup ' . esc_attr( $item['css_classes'] ) . ' ' . $item['inline_list'] . ' '.$element_required . ' ' . $element_required.'-'.$item_id. '">';

		if($item['required'] && 'checkbox' === $type){
			$item_id = $item['custom_id'];
			$oninvalid = "this.setCustomValidity('Please check the any one of the checkbox if you want to proceed.')";
			$oninput = "setCustomValidity('')";
			// $html .='<input type="text" name="valid-'. $item_id .'" required="required" class="cs-validation-ck cs-validation-ck'. $item_id . '" oninvalid="' .$oninvalid .'" oninput="'. $oninput .'">';
			$html .='<input type="text" name="valid-'. $item_id .'" required="required" class="cs-validation-ck cs-validation-ck'. $item_id . '">';
			$html .= '<script type="text/javascript"> jQuery("document").ready(function(){
					jQuery(".'. $element_required .'-'. $item_id .' .checkbox").change(function(){
						if (jQuery(".'.$element_required.'-'. $item_id .' .checkbox:checked").length > 0){
							jQuery("input.cs-validation-ck'. $item_id . '").val("1");
					//console.log("checked");
						}else{
					// console.log("not checked");
							jQuery("input.cs-validation-ck'. $item_id . '").val("");

						}
			});});	</script>';
		}
		
		foreach ( $options as $key => $option ) {
			$element_id = $item['custom_id'] . $key;
			$html_id = $this->get_attribute_id( $item ) . '-' . $key;
			$option_label = $option;
			$option_value = $option;
			if ( false !== strpos( $option, '|' ) ) {
				list( $option_label, $option_value ) = explode( '|', $option );
			}

			$this->add_render_attribute(
				$element_id,
				[
					'type' => $type,
					'value' => $option_value,
					'id' => $html_id,
					'name' => $this->get_attribute_name( $item ) . ( ( 'checkbox' === $type && count( $options ) > 1 ) ? '[]' : '' ),
				]
			);

			if ( ! empty( $item['field_value'] ) && $option_value === $item['field_value'] ) {
				$this->add_render_attribute( $element_id, 'checked', 'checked' );
			}

			if ( $item['required'] && 'radio' === $type ) {
				$this->add_required_attribute( $element_id );
			}
			// elseif( $item['required'] && 'checkbox' === $type ){
			// 	$this->add_required_attribute( $element_id );

			// }

			$html .= '<span class="elementor-field-option"><input ' . $this->get_render_attribute_string( $element_id ) . ' class="checkbox"> <label for="' . $html_id . '">' . $option_label . '</label></span>';
		}
		$html .= '</div>';
	}

	return $html;
}
Step : 3 Add below css

/* Form validation */
input.cs-validation-ck {
opacity: 0;
width: 0px !important;
height: 0px !important;
padding: 1px !important;
margin: 0 !important;
border: none !important;

**Comment by WarMagic25** [comment]
> > I just tried this. It worked like magic. Thank you so much. The line numbers won't match so use Find in Page to look for **'checkbox',** and **&& 'radio' === $type** and remove them.
> > In this case, all the checkbox options must be selected. Any idea how to limit to at least one?
> 
> The below code is working fine for me Step: 1 elementor-pro\modules\forms\widgets\form.php
> 
> line 147 - function name " register_controls " - hide the "checkbox"
> 
> ```
> $repeater->add_control(
> 		'required',
> 		[
> 			'label' => esc_html__( 'Required', 'elementor-pro' ),
> 			'type' => Controls_Manager::SWITCHER,
> 			'return_value' => 'true',
> 			'default' => '',
> 			'conditions' => [
> 				'terms' => [
> 					[
> 						'name' => 'field_type',
> 						'operator' => '!in',
> 						'value' => [
> 							// 'checkbox',
> 							'recaptcha',
> 							'recaptcha_v3',
> 							'hidden',
> 							'html',
> 							'step',
> 						],
> 					],
> 				],
> 			],
> 		]
> 	);
> ```
> 
> Step : 2 elementor-pro\modules\forms\classes line 150 Replace the below function
> 
> ```
> protected function make_radio_checkbox_field( $item, $item_index, $type ) {
> 	$options = preg_split( "/\\r\\n|\\r|\\n/", $item['field_options'] );
> 	$html = '';
> 	if ( $options ) {
> 
> 		
> 		$element_required = ($item['required'] && 'checkbox' === $type)?"element_required":"";
> 		$item_id = $item['custom_id'];
> 		$html .= '<div class="elementor-field-subgroup ' . esc_attr( $item['css_classes'] ) . ' ' . $item['inline_list'] . ' '.$element_required . ' ' . $element_required.'-'.$item_id. '">';
> 
> 		if($item['required'] && 'checkbox' === $type){
> 			$item_id = $item['custom_id'];
> 			$oninvalid = "this.setCustomValidity('Please check the any one of the checkbox if you want to proceed.')";
> 			$oninput = "setCustomValidity('')";
> 			// $html .='<input type="text" name="valid-'. $item_id .'" required="required" class="cs-validation-ck cs-validation-ck'. $item_id . '" oninvalid="' .$oninvalid .'" oninput="'. $oninput .'">';
> 			$html .='<input type="text" name="valid-'. $item_id .'" required="required" class="cs-validation-ck cs-validation-ck'. $item_id . '">';
> 			$html .= '<script type="text/javascript"> jQuery("document").ready(function(){
> 					jQuery(".'. $element_required .'-'. $item_id .' .checkbox").change(function(){
> 						if (jQuery(".'.$element_required.'-'. $item_id .' .checkbox:checked").length > 0){
> 							jQuery("input.cs-validation-ck'. $item_id . '").val("1");
> 					//console.log("checked");
> 						}else{
> 					// console.log("not checked");
> 							jQuery("input.cs-validation-ck'. $item_id . '").val("");
> 
> 						}
> 			});});	</script>';
> 		}
> 		
> 		foreach ( $options as $key => $option ) {
> 			$element_id = $item['custom_id'] . $key;
> 			$html_id = $this->get_attribute_id( $item ) . '-' . $key;
> 			$option_label = $option;
> 			$option_value = $option;
> 			if ( false !== strpos( $option, '|' ) ) {
> 				list( $option_label, $option_value ) = explode( '|', $option );
> 			}
> 
> 			$this->add_render_attribute(
> 				$element_id,
> 				[
> 					'type' => $type,
> 					'value' => $option_value,
> 					'id' => $html_id,
> 					'name' => $this->get_attribute_name( $item ) . ( ( 'checkbox' === $type && count( $options ) > 1 ) ? '[]' : '' ),
> 				]
> 			);
> 
> 			if ( ! empty( $item['field_value'] ) && $option_value === $item['field_value'] ) {
> 				$this->add_render_attribute( $element_id, 'checked', 'checked' );
> 			}
> 
> 			if ( $item['required'] && 'radio' === $type ) {
> 				$this->add_required_attribute( $element_id );
> 			}
> 			// elseif( $item['required'] && 'checkbox' === $type ){
> 			// 	$this->add_required_attribute( $element_id );
> 
> 			// }
> 
> 			$html .= '<span class="elementor-field-option"><input ' . $this->get_render_attribute_string( $element_id ) . ' class="checkbox"> <label for="' . $html_id . '">' . $option_label . '</label></span>';
> 		}
> 		$html .= '</div>';
> 	}
> 
> 	return $html;
> }
> ```
> 
> Step : 3 Add below css
> 
> /* Form validation */ input.cs-validation-ck { opacity: 0; width: 0px !important; height: 0px !important; padding: 1px !important; margin: 0 !important; border: none !important; }



hi i tested and is works but how to make this permanent? After update the elementor pro the modified code is removed..

**Comment by manig-metaweb** [comment]
> > > I just tried this. It worked like magic. Thank you so much. The line numbers won't match so use Find in Page to look for **'checkbox',** and **&& 'radio' === $type** and remove them.
> > > In this case, all the checkbox options must be selected. Any idea how to limit to at least one?
> > 
> > 
> > The below code is working fine for me Step: 1 elementor-pro\modules\forms\widgets\form.php
> > line 147 - function name " register_controls " - hide the "checkbox"
> > ```
> > $repeater->add_control(
> > 		'required',
> > 		[
> > 			'label' => esc_html__( 'Required', 'elementor-pro' ),
> > 			'type' => Controls_Manager::SWITCHER,
> > 			'return_value' => 'true',
> > 			'default' => '',
> > 			'conditions' => [
> > 				'terms' => [
> > 					[
> > 						'name' => 'field_type',
> > 						'operator' => '!in',
> > 						'value' => [
> > 							// 'checkbox',
> > 							'recaptcha',
> > 							'recaptcha_v3',
> > 							'hidden',
> > 							'html',
> > 							'step',
> > 						],
> > 					],
> > 				],
> > 			],
> > 		]
> > 	);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Step : 2 elementor-pro\modules\forms\classes line 150 Replace the below function
> > ```
> > protected function make_radio_checkbox_field( $item, $item_index, $type ) {
> > 	$options = preg_split( "/\\r\\n|\\r|\\n/", $item['field_options'] );
> > 	$html = '';
> > 	if ( $options ) {
> > 
> > 		
> > 		$element_required = ($item['required'] && 'checkbox' === $type)?"element_required":"";
> > 		$item_id = $item['custom_id'];
> > 		$html .= '<div class="elementor-field-subgroup ' . esc_attr( $item['css_classes'] ) . ' ' . $item['inline_list'] . ' '.$element_required . ' ' . $element_required.'-'.$item_id. '">';
> > 
> > 		if($item['required'] && 'checkbox' === $type){
> > 			$item_id = $item['custom_id'];
> > 			$oninvalid = "this.setCustomValidity('Please check the any one of the checkbox if you want to proceed.')";
> > 			$oninput = "setCustomValidity('')";
> > 			// $html .='<input type="text" name="valid-'. $item_id .'" required="required" class="cs-validation-ck cs-validation-ck'. $item_id . '" oninvalid="' .$oninvalid .'" oninput="'. $oninput .'">';
> > 			$html .='<input type="text" name="valid-'. $item_id .'" required="required" class="cs-validation-ck cs-validation-ck'. $item_id . '">';
> > 			$html .= '<script type="text/javascript"> jQuery("document").ready(function(){
> > 					jQuery(".'. $element_required .'-'. $item_id .' .checkbox").change(function(){
> > 						if (jQuery(".'.$element_required.'-'. $item_id .' .checkbox:checked").length > 0){
> > 							jQuery("input.cs-validation-ck'. $item_id . '").val("1");
> > 					//console.log("checked");
> > 						}else{
> > 					// console.log("not checked");
> > 							jQuery("input.cs-validation-ck'. $item_id . '").val("");
> > 
> > 						}
> > 			});});	</script>';
> > 		}
> > 		
> > 		foreach ( $options as $key => $option ) {
> > 			$element_id = $item['custom_id'] . $key;
> > 			$html_id = $this->get_attribute_id( $item ) . '-' . $key;
> > 			$option_label = $option;
> > 			$option_value = $option;
> > 			if ( false !== strpos( $option, '|' ) ) {
> > 				list( $option_label, $option_value ) = explode( '|', $option );
> > 			}
> > 
> > 			$this->add_render_attribute(
> > 				$element_id,
> > 				[
> > 					'type' => $type,
> > 					'value' => $option_value,
> > 					'id' => $html_id,
> > 					'name' => $this->get_attribute_name( $item ) . ( ( 'checkbox' === $type && count( $options ) > 1 ) ? '[]' : '' ),
> > 				]
> > 			);
> > 
> > 			if ( ! empty( $item['field_value'] ) && $option_value === $item['field_value'] ) {
> > 				$this->add_render_attribute( $element_id, 'checked', 'checked' );
> > 			}
> > 
> > 			if ( $item['required'] && 'radio' === $type ) {
> > 				$this->add_required_attribute( $element_id );
> > 			}
> > 			// elseif( $item['required'] && 'checkbox' === $type ){
> > 			// 	$this->add_required_attribute( $element_id );
> > 
> > 			// }
> > 
> > 			$html .= '<span class="elementor-field-option"><input ' . $this->get_render_attribute_string( $element_id ) . ' class="checkbox"> <label for="' . $html_id . '">' . $option_label . '</label></span>';
> > 		}
> > 		$html .= '</div>';
> > 	}
> > 
> > 	return $html;
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Step : 3 Add below css
> > /* Form validation */ input.cs-validation-ck { opacity: 0; width: 0px !important; height: 0px !important; padding: 1px !important; margin: 0 !important; border: none !important; }
> 
> hi i tested and is works but how to make this permanent? After update the elementor pro the modified code is removed..

Hi @WarMagic25 ,
   I am trying to find a permanent solution but they didn't provide any hooks related to these form fields. so they can only fix this issue on his next version or should provide any filter hooks. 

Thanks

**Comment by WarMagic25** [comment]
> > > > I just tried this. It worked like magic. Thank you so much. The line numbers won't match so use Find in Page to look for **'checkbox',** and **&& 'radio' === $type** and remove them.
> > > > In this case, all the checkbox options must be selected. Any idea how to limit to at least one?
> > > 
> > > 
> > > The below code is working fine for me Step: 1 elementor-pro\modules\forms\widgets\form.php
> > > line 147 - function name " register_controls " - hide the "checkbox"
> > > ```
> > > $repeater->add_control(
> > > 		'required',
> > > 		[
> > > 			'label' => esc_html__( 'Required', 'elementor-pro' ),
> > > 			'type' => Controls_Manager::SWITCHER,
> > > 			'return_value' => 'true',
> > > 			'default' => '',
> > > 			'conditions' => [
> > > 				'terms' => [
> > > 					[
> > > 						'name' => 'field_type',
> > > 						'operator' => '!in',
> > > 						'value' => [
> > > 							// 'checkbox',
> > > 							'recaptcha',
> > > 							'recaptcha_v3',
> > > 							'hidden',
> > > 							'html',
> > > 							'step',
> > > 						],
> > > 					],
> > > 				],
> > > 			],
> > > 		]
> > > 	);
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Step : 2 elementor-pro\modules\forms\classes line 150 Replace the below function
> > > ```
> > > protected function make_radio_checkbox_field( $item, $item_index, $type ) {
> > > 	$options = preg_split( "/\\r\\n|\\r|\\n/", $item['field_options'] );
> > > 	$html = '';
> > > 	if ( $options ) {
> > > 
> > > 		
> > > 		$element_required = ($item['required'] && 'checkbox' === $type)?"element_required":"";
> > > 		$item_id = $item['custom_id'];
> > > 		$html .= '<div class="elementor-field-subgroup ' . esc_attr( $item['css_classes'] ) . ' ' . $item['inline_list'] . ' '.$element_required . ' ' . $element_required.'-'.$item_id. '">';
> > > 
> > > 		if($item['required'] && 'checkbox' === $type){
> > > 			$item_id = $item['custom_id'];
> > > 			$oninvalid = "this.setCustomValidity('Please check the any one of the checkbox if you want to proceed.')";
> > > 			$oninput = "setCustomValidity('')";
> > > 			// $html .='<input type="text" name="valid-'. $item_id .'" required="required" class="cs-validation-ck cs-validation-ck'. $item_id . '" oninvalid="' .$oninvalid .'" oninput="'. $oninput .'">';
> > > 			$html .='<input type="text" name="valid-'. $item_id .'" required="required" class="cs-validation-ck cs-validation-ck'. $item_id . '">';
> > > 			$html .= '<script type="text/javascript"> jQuery("document").ready(function(){
> > > 					jQuery(".'. $element_required .'-'. $item_id .' .checkbox").change(function(){
> > > 						if (jQuery(".'.$element_required.'-'. $item_id .' .checkbox:checked").length > 0){
> > > 							jQuery("input.cs-validation-ck'. $item_id . '").val("1");
> > > 					//console.log("checked");
> > > 						}else{
> > > 					// console.log("not checked");
> > > 							jQuery("input.cs-validation-ck'. $item_id . '").val("");
> > > 
> > > 						}
> > > 			});});	</script>';
> > > 		}
> > > 		
> > > 		foreach ( $options as $key => $option ) {
> > > 			$element_id = $item['custom_id'] . $key;
> > > 			$html_id = $this->get_attribute_id( $item ) . '-' . $key;
> > > 			$option_label = $option;
> > > 			$option_value = $option;
> > > 			if ( false !== strpos( $option, '|' ) ) {
> > > 				list( $option_label, $option_value ) = explode( '|', $option );
> > > 			}
> > > 
> > > 			$this->add_render_attribute(
> > > 				$element_id,
> > > 				[
> > > 					'type' => $type,
> > > 					'value' => $option_value,
> > > 					'id' => $html_id,
> > > 					'name' => $this->get_attribute_name( $item ) . ( ( 'checkbox' === $type && count( $options ) > 1 ) ? '[]' : '' ),
> > > 				]
> > > 			);
> > > 
> > > 			if ( ! empty( $item['field_value'] ) && $option_value === $item['field_value'] ) {
> > > 				$this->add_render_attribute( $element_id, 'checked', 'checked' );
> > > 			}
> > > 
> > > 			if ( $item['required'] && 'radio' === $type ) {
> > > 				$this->add_required_attribute( $element_id );
> > > 			}
> > > 			// elseif( $item['required'] && 'checkbox' === $type ){
> > > 			// 	$this->add_required_attribute( $element_id );
> > > 
> > > 			// }
> > > 
> > > 			$html .= '<span class="elementor-field-option"><input ' . $this->get_render_attribute_string( $element_id ) . ' class="checkbox"> <label for="' . $html_id . '">' . $option_label . '</label></span>';
> > > 		}
> > > 		$html .= '</div>';
> > > 	}
> > > 
> > > 	return $html;
> > > }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Step : 3 Add below css
> > > /* Form validation */ input.cs-validation-ck { opacity: 0; width: 0px !important; height: 0px !important; padding: 1px !important; margin: 0 !important; border: none !important; }
> > 
> > 
> > hi i tested and is works but how to make this permanent? After update the elementor pro the modified code is removed..
> 
> Hi @WarMagic25 , I am trying to find a permanent solution but they didn't provide any hooks related to these form fields. so they can only fix this issue on his next version or should provide any filter hooks.
> 
> Thanks

Hi,, i try the support and they not resolve nothing.......

**Comment by WarMagic25** [comment]
a method to use the functions.php? is maybe a solution, or a script that rewrite the costom code and check the version as a reference. or is maybe a plugin that offers a options like this ?
