### ISSUE TITLE
Remove Default Border Left in Nav Menu Dropdown CSS

### ISSUE THREAD

**Issue by katart** [pojome/elementor#2496]
## Description

I've noticed a default 8px border left in the nav-menu dropdown styles. I've tried to remove the border within the widget settings but the CSS will not change. Here is the CSS code:

```
.elementor-nav-menu--dropdown a, .elementor-nav-menu--dropdown a:focus, .elementor-nav-menu--dropdown a:hover {
    text-shadow: none;
    border-left: 8px solid transparent;
}
```

View the attached screenshot:
![screen shot 2017-09-26 at 5 10 44 pm](https://user-images.githubusercontent.com/1799645/30884693-92805eec-a2de-11e7-9aab-8fe1c6119694.png)

Any ideas on how to remove this border?

## Environment
		
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: 5.6.37
	PHP Version: 5.4.45
	PHP Max Input Vars: 1000
	PHP Max Post Size: 64M
	GD Installed: Yes
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.8.2
	Site URL: http://fny.fnytesting.com
	Home URL: http://fny.fnytesting.com
	WP Multisite: No
	Max Upload Size: 64 MB
	Memory limit: 40M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: America/New_York
	Debug Mode: Active

== Theme ==
	Name: GeneratePress Child
	Version: 0.1
	Author: Tom Usborne
	Child Theme: Yes
	Parent Theme Name: GeneratePress
	Parent Theme Version: 1.4
	Parent Theme Author: Tom Usborne

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3218.0 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 1.7.6
		Author: Elementor.com

	Elementor Extras
		Version: 1.3.0
		Author: Namogo

	Elementor Pro
		Version: 1.9.0
		Author: Elementor.com

	GP Premium
		Version: 1.4.3
		Author: Tom Usborne

	WP Smush
		Version: 2.7.4.1
		Author: WPMU DEV

== Debug ==
	Errors: 
		SyntaxError: Invalid or unexpected token
			at http://fny.fnytesting.com/wp-admin/post.php?post=12&action=elementor - 4:37
			2017-09-18 15:56 +00:00

		SyntaxError: missing ) after argument list
			at http://fny.fnytesting.com/wp-admin/post.php?post=12&action=elementor - 4:29
			2017-09-18 15:55 +00:00
			x 2 times

		SyntaxError: missing ) after argument list
			at http://fny.fnytesting.com/wp-admin/post.php?post=12&action=elementor - 4:19
			2017-09-18 15:55 +00:00
			x 7 times

		SyntaxError: Unexpected string
			at http://fny.fnytesting.com/wp-admin/post.php?post=12&action=elementor - 4:19
			2017-09-18 15:55 +00:00

		SyntaxError: missing ) after argument list
			at http://fny.fnytesting.com/wp-admin/post.php?post=12&action=elementor - 4:7
			2017-09-18 15:55 +00:00

		SyntaxError: Invalid or unexpected token
			at http://fny.fnytesting.com/wp-admin/post.php?post=12&action=elementor - 4:24
			2017-09-18 15:55 +00:00

		SyntaxError: Unexpected token .
			at http://fny.fnytesting.com/wp-admin/post.php?post=12&action=elementor - 17:23
			2017-09-18 15:52 +00:00
			x 2 times

		SyntaxError: Unexpected token .
			at http://fny.fnytesting.com/wp-admin/post.php?post=12&action=elementor - 17:21
			2017-09-18 15:49 +00:00

		SyntaxError: Unexpected token ;
			at http://fny.fnytesting.com/wp-admin/post.php?post=12&action=elementor - 12:42
			2017-09-18 15:40 +00:00

		SyntaxError: Unexpected token .
			at http://fny.fnytesting.com/wp-admin/post.php?post=12&action=elementor - 12:26
			2017-09-18 15:39 +00:00
			x 8 times

**Comment by arielk** [comment]
Fixed Pro v1.9.4

**Comment by vovkasolovev** [comment]
I confirm that there is an unnecessary 8px border in frontend.min.css
```
ul.elementor-nav-menu--dropdown a, ul.elementor-nav-menu--dropdown a:focus, ul.elementor-nav-menu--dropdown a:hover {
    text-shadow: none;
    border-left: 8px solid transparent;
}
```

**Comment by scarydakis** [comment]
I can confirm that this is still present!

**Comment by cirkut** [comment]
Bringing this up that this issue is still relevant with the current Elementor & Elementor Pro versions (2.9.7 and 2.9.2 pro). Please remove the border-left by default, even setting a 0px border on the dropdown item in the widget does not fix this issue. The only way to solve this is with custom CSS, and is incredibly frustrating.

**Comment by 319heads** [comment]
This needs to be re-opened as this issue still exists in Elementor 3+ with both dropdowns and mobile menus adding the 8px left border with now settings to remove it. This has got to go:

```
ul.elementor-nav-menu--dropdown a, ul.elementor-nav-menu--dropdown a:focus, ul.elementor-nav-menu--dropdown a:hover {
    text-shadow: none;
    border-left: 8px solid transparent;
    border-left-width: 8px;
    border-left-style: solid;
    border-left-color: transparent;
}
```

**Comment by cirkut** [comment]
@shilo-ey Can we get this reopened? This looks awful on desktop dropdown menu. I know this was meant to add left padding to submenus on mobile layouts, but this is causing completely erroneous left padding on dropdowns when viewing on desktop.

Really, we should be setting left padding of dropdown menus in Elementor, not having 8px be the default. There are use-cases where on mobile, I would want to have submenus simply be a different color, and not have additional left padding for visual nesting.

**Comment by madebyreformat** [comment]
Agreed not even sure what it's there for. I've just stuck some CSS to fix in the meantime on the nav element itself

`selector ul.elementor-nav-menu--dropdown a, selector ul.elementor-nav-menu--dropdown a:focus, selector ul.elementor-nav-menu--dropdown a:hover {
    border-left:0;
}`

**Comment by cirkut** [comment]
@arielk Think we can get a solution for this? There is no reason for the left border to be there on the desktop breakpoint. Or alternatively, this needs to be a slider/range on the menu so we can adjust the left border size ourselves.

**Comment by bkjproductions** [comment]
Same as issue 13866 from 2021:
https://github.com/elementor/elementor/issues/13866
Still there in Elementor Pro v. 3.7.1

**Comment by UltraMarathonEER** [comment]
Still there in Elementor Pro 3.7.7

**Comment by jaysonwebtel** [comment]
This still exists in 3.9.2 - Very not cool... We need the option to enable or disable this, or to even control it if need be...   Its coming from  /plugins/elementor-pro/assets/css/widget-nav-menu.min.css as far as i can see when I regenerate the CSS using Elementor - Tools.

**Comment by anwer-456** [comment]
Hey, I have wasted a lot of time on this anyhow I've fixed this via custom css in Menu Widget->Advanced->Custom CSS which replaced the border-left:8px which is added by elementor itself.

/* CSS Code */
ul.elementor-nav-menu--dropdown a{
border-left:0px !important;
}

This is a permenant solution. For WP Tutorials subscribe this Channel https://www.youtube.com/channel/UC0rAvYilKy5RoY-5KutFz0g

Thank you!

**Comment by anwer-456** [comment]
Hello, I've spent quite a bit of time on this issue. Nonetheless, I managed to resolve it by using custom CSS within the Menu Widget settings under Advanced options. I replaced the default border-left value of 8px, which is automatically added by Elementor.

Here's the CSS code I used:
ul.elementor-nav-menu--dropdown a {
border-left: 0px !important;
}

This solution is permanent. If you're interested in WordPress tutorials, feel free to subscribe to this YouTube channel: https://www.youtube.com/channel/UC0rAvYilKy5RoY-5KutFz0g

Thank you!

**Comment by anwer-456** [comment]
Hello, I've spent quite a bit of time on this issue. Nonetheless, I managed to resolve it by using custom CSS within the Menu Widget settings under Advanced options. I replaced the default border-left value of 8px, which is automatically added by Elementor.

Here's the CSS code I used:
ul.elementor-nav-menu--dropdown a {
border-left: 0px !important;
}

Please refer to the linked [screenshot](https://imageupload.io/en/iMhQ8d4ylgNmIcT) for clarity!

This solution is permanent. If you're interested in WordPress tutorials, feel free to subscribe to this YouTube channel: https://www.youtube.com/channel/UC0rAvYilKy5RoY-5KutFz0g

Thank you!

**Comment by maryisdead** [comment]
@arielk This issue still exists. Can this be re-opened?

**Comment by fernandesadrian** [comment]
This issue still exists in the latest version v3.23.3 as well. This

**Comment by timoschaffner** [comment]
Issue STILL persists! Please reopen.
