### ISSUE TITLE
[Feature Request] Adaptive/Auto Height Image Carousel

### ISSUE THREAD

**Issue by katart** [pojome/elementor#2539]
It would be nice to add the Auto or Adaptive Height option to the Image Carousel. The Carousel looks awkward when some images are vertical in a mostly horizontal slider.

**Comment by jayalove** [comment]
I second this request 😉

**Comment by the-crusty** [comment]
Yes, that would really be a very welcome enhancement!

**Comment by parfilov** [comment]
I need it too.

**Comment by dollhauss** [comment]
+1

**Comment by humemedia** [comment]
+1

**Comment by black-eye** [comment]
+1

**Comment by ronald-edge** [comment]
+1 Adaptive Height for Image (and Testimonial Carousel #6327)

**Comment by stephin-gasper** [comment]
+1

**Comment by ronald-edge** [comment]
I switched to the Jet Elements Testimonials (carousel) plugin to be able to display testimonials of varying heights in a visually pleasing way.

https://crocoblock.com/jetelements/
https://jetelements.zemez.io/testimonials/

**Comment by contempoinc** [comment]
Another +1 even though this is two years old.

**Comment by Damian2Cubed** [comment]
+1

Hi guys, just like rest of you I was looking for this feature.

I did little workaround:
```
testimonialsAutoHeight('.elementor-swiper-button-next');
testimonialsAutoHeight('.elementor-swiper-button-prev');
  
function testimonialsAutoHeight(btn) {
	  $('body').on('click', btn, function() {
		  console.log('Clicked');
		  
		  var testimonial_height = $('.swiper-slide-active .elementor-testimonial').height();
		  testimonial_height = testimonial_height + 80;
		  
		  $('.elementor-widget-testimonial-carousel .elementor-widget-container').css('height', testimonial_height);
	  });
}
```

**Comment by m0n0mind** [comment]
are there any plans that this feature will be added anytime soon?

**Comment by kokers** [comment]
Solution to access swiper object directly:
```
var elementorSwiper = document.querySelector('.swiper-container').swiper;
elementorSwiper.params.autoHeight = true;
```

put this on `$(window).load(function(){})` or similar.

**Comment by jj-carlson** [comment]
+1
Please, would really appreciate this being implemented. JS workarounds are nice, but a simple setting change would be preferred.

**Comment by hubertq** [comment]
+1

**Comment by 3mpstudio** [comment]
+1

**Comment by artheadsgames** [comment]
Really need this!

**Comment by VL375** [comment]
I've had a similar issue an found this very simple solution with a short CSS code: https://elementorcodes.com/elementor-justified-image-gallery-carousel/

Just read the article and watch the video and follow the steps. Worked fine for me, now horizontal and vertical images in the carousel are all aligned at the same height. If you need help with this, let me now.

**Comment by mrandraspal** [comment]
I would  like to have this feature too very much. This (https://elementorcodes.com/elementor-justified-image-gallery-carousel/) seems hard to manage in editor when you have many (20-30) images.
There are justified gallery plugins but no carousel, which is weird as this feature seems so important.

**Comment by Lincox** [comment]
Hi everyone, I find the way to do this myself, I did it for image carousel for example

```
var carousel = jQuery('.elementor-image-carousel-wrapper');

carousel.each(function() {
	_this = $(this);
	var swiper = _this.data('swiper');
	var height = _this.find('.swiper-slide-active .swiper-slide-inner').height();
	_this.css('height', height);

	swiper.on( 'slideChangeTransitionStart', function() {
		height = _this.find('.swiper-slide-active .swiper-slide-inner').height();
		_this.css('height', height);
	})
})
```

Then you just need to call that in window on load and problem is solved
Btw, if you want the transformed height to be smooth, you just need to set
```
.elementor-image-carousel-wrapper {
  transition: 0.5s ease;
}
```

**Comment by MichaelDarko** [comment]
4.5 years since the request a still no fix. You create multiple crappy carousel / slider widgets and then you barely maintain them because there is too many of them. Can't you just create one universal carousel / slider builder? We would be able to build whatever we need and you would be able to maintain it.

**Comment by symplTech** [comment]
+1

**Comment by acornavi** [comment]
Why is Elementor neglecting basic corrections and updates of the widgets for five years? Breakdance and Bricks are already much better with smaller teams and without funding.

**Comment by jamie49** [comment]
+1

I'm shocked this is still not available.

I had to implement the following code in order to get the "Slides" widget working with adaptive height.

`<script>
    $(function(){

        function adjustCarouselHeight(){
            var carousel_height = $(".swiper-slide-active .swiper-slide-contents").height() + 110;
            $(".elementor-swiper").css("height", carousel_height);
        }

        // Set height on page load (ensures first animation is smooth)
        $(window).on("load", function(){
            adjustCarouselHeight();
        });
        
        // Adjust height on click of arrows or page dots
        $("body").on("click", ".elementor-swiper-button-prev, .elementor-swiper-button-next, .swiper-pagination-bullet", function(){
            adjustCarouselHeight();
        });

        // Adjust height after swiping with mouseup event
        // .carousel-section is the full width container that the carousel sits inside of
        $("body").on("mouseup", ".carousel-section", function(){
            setTimeout(function(){
                adjustCarouselHeight();
            }, 100); // small delay, wait for Swiper to apply dom changes
        });

    });
</script>`

Each individual slide has a transparent BG. This CSS rule is also needed:
`selector .elementor-swiper { background-color: #fff; transition: ease height 300ms; }`

**Comment by vladimir-boyko** [comment]
// Change class name .swiper--auto-height for carousel images

const swiperAutoHeight = () => {
	window.addEventListener( 'load', () => {
		const elementorSwiperCarousels = document.querySelectorAll( '.swiper--auto-height .swiper-container' );

		if ( elementorSwiperCarousels.length !== 0 ) {
			for ( const elementorSwiperCarousel of elementorSwiperCarousels ) {
				const elementorSwiper = elementorSwiperCarousel.swiper;
				const elementorSwiperParams = elementorSwiper.params;
				elementorSwiper.destroy();

				const swiper = new Swiper ( elementorSwiperCarousel, {
					...elementorSwiperParams,

					// Custom params
					autoHeight: true
				});
			};
		};
	});
};

swiperAutoHeight();

https://gist.github.com/vladimir-boyko/bd4b0e857bd2e83331dedf47adf7a584

**Comment by speedxcz** [comment]
+1

**Comment by Samg381** [comment]
+1

**Comment by gerardreches** [comment]
+1, and it is the same with the new Loop Carousel.

**Comment by ismaeel-yaghoubi** [comment]
You can add 
```
.swiper-slide{
        height: 100%
}
```
