### ISSUE TITLE
Why elementor add class ".elementor-invisible" without any prior settings?

### ISSUE THREAD

**Issue by webangon** [pojome/elementor#2806]
Sometimes `elementor-invisible` class is added. There is no settings like make section/column hidden. Its annoying because I have to delete that section and add again to  work with.

**Comment by bainternet** [comment]
@webangon can you provide an example?

**Comment by webangon** [comment]
@bainternet 
![1](https://user-images.githubusercontent.com/7946657/33193299-d2290760-d0f1-11e7-8007-144d1a2a164b.png)

**Comment by bainternet** [comment]
@webangon,

I mean can you provide an example of when it happens?
how to reproduce?

The `.elementor-invisible` is usually related to either responsive settings or animations, are you using/defining any before it happens?

**Comment by webangon** [comment]
Here is the live url - http://plugins.webangon.com/khara/ashelement/element-grid-pricing/
I have to add important rule to make it visible . 
![untitled](https://user-images.githubusercontent.com/7946657/33343293-f4021852-d4ae-11e7-9d30-ab78a52fa170.jpg)

I have tested with device visibilty and elementor-invisible class is accompanied by extra class like elementor-hidden-phone.  But in my case there is such extra class like elementor-hidden-phone. 
![2](https://user-images.githubusercontent.com/7946657/33343382-53cefe30-d4af-11e7-907b-ab8e2af9f27c.jpg)

Lastly this is not a big issue. Maybe this issue was a ghostly one .

**Comment by shapsmedia** [comment]
Hey there,
I've this issue too. It occurs when using animation like "fade in" for example and disabling Javascript. 

**For instance - Fade in a heading:**

1. Create Animation for an element/widget
2. Save and preview on preview page
3. JS Enabled: Everything looks fine
**HTML:**
`<div data-id="7dbabf2" class="elementor-element elementor-element-7dbabf2 animated elementor-widget elementor-widget-heading fadeInLeft" data-settings="{"_animation":"fadeInLeft"}" data-element_type="heading.default">
				<div class="elementor-widget-container">
			<h2 class="elementor-heading-title elementor-size-default">Heading</h2>		</div>
				</div>
`
4. JS Disabled(Through switcher chrome extension): No animation and the widget stays hidden. Obviously the class "elementor-invisible" causes this. 
**HTML**
`<div data-id="7dbabf2" class="elementor-element elementor-element-7dbabf2 animated fadeInLeft elementor-invisible elementor-widget elementor-widget-heading" data-settings="{"_animation":"fadeInLeft"}" data-element_type="heading.default">
				<div class="elementor-widget-container">
			<h2 class="elementor-heading-title elementor-size-default">Heading</h2>		</div>
				</div>`

I'm not sure if I miss any settings but couldn't find a specific option. A little detrimental that this pure css animation depend on js.

Any idea?

Thanks for help.

**Comment by Zer0ne83** [comment]
Same scenario so I won't bother reiterating it but just wanted to confirm the same issue somewhat randomly occurs for me. That is, pages built with elementor-elements with animations applied to them will randomly add an elementor-invisible class to itself and siblings. Sometimes the invisible class is applied consistently (i.e. on every refresh of the offending elementor-built page) and sometimes simply refreshing the page sees the invisible class NOT applied. It's not 'Responsive' settings (none applied) and there's no JS/JQuery conflicts or errors that I can see or are reported via console. I'm just avoiding elementor's animation integration and applying Animate.css via their own plugin with tags.

**Comment by blaisck** [comment]
I have the same problem here.
Yesterday I build some pop-up and it was fine until today I update my Elementor.
My image on the pop-up is gone, and the problem is `elementor-invisible: invisible` suddenly appear from no where.

**Comment by Mulli** [comment]
Seems like same issue...
Generated template with image that is using slide in animation.
How to regenerate:
1. Keep some design with the above animation as template
2. Generate "single" builder template for posts - import the template from (1)
3. Replace static definition with dynamic (to apply to each post that meets the criteria)
Booom!
The image is not there anymore.
Tried to use "feature image" - no luck.
Now, I am stuck
:-)

**Comment by Mulli** [comment]
Further study:
1. Removing the animation definition - reveals the image.
2. Setting animation on image - adds the class: .elementor-invisible
Note:
When animation is ON the image is displayed & removed several times.
My guess - The class is for quick & dirty solution. Should be fixed.

**Comment by erickmarcia** [comment]
Hola, Tengo el mismo problema y aun nose como solucionarlo

**Comment by dimative** [comment]
I have the same problem here. Anyone found solution for this issue?

**Comment by jerehupanen** [comment]
Yeah still an existing issue. It hides the template on some pages, not on all.

**Comment by American-Ledger** [comment]
I had this problem and I was able to resolve it. 

In my case, I had an embedded HTML Code section that had an extra "</div>" tag without a corresponding <div> in front of it.  The Elementor HTML Code editor was showing red-X on the offending line.

**Comment by jomarieminney** [comment]
This happened to me today, after over an hour I finally figured it out when I came across this thread. Honestly Elementor the number of times tickets like these are still open after 3 (THREE!) years is mind boggling. Are you going to use some of that new investment money to actually fix your product so we don't all waste our time banging our heads against walls?

**Comment by Zebirdman** [comment]
happened to us this week. Animations linked to imbedded iframes caused the elements to remain hidden on the actual page although on elementor it showed them as working correctly.

**Comment by dkoziak** [comment]
same issue, animations cause it to be hidden.

**Comment by edwardm** [comment]
Yep can confirm still happening. I was testing out animations on a section. Then decided to remove them, now "elementor-invisible" class appears in the DOM, no matter what I do. The motion effects section is completely reset and nothing applied.

**Comment by tseggai** [comment]
Simple solution//

Deactivate the "JetPopUp" plugin. If that's not the case, then try deactivating all plugins and turn them on one by one while testing your page until you identify which one does. 

Good luck

**Comment by harksha** [comment]
sadly still happening

**Comment by hking1991** [comment]
Still an issue. Happens on every site I build with Elementor - absolute pain in the arse!

**Comment by Tannyr** [comment]
Invisible content in Elementor is usually related to animations failing to load.  The content begins hidden, an animation script is triggered, and they animate into visibility. The reason animations fail to load is usually because there is a javascript error on the page.  You can right click -> inspect the page, and check the console to see what the error is.  (It's the red text).  If you do a bit of sleuthing, you can find where the error originates.  In my case, it was a typed.js call on an widget that had an incorrect identifier.  I removed the row with the bad widget and everything came back.

**Comment by kushagra99** [comment]
> Sometimes `elementor-invisible` class is added. There is no settings like make section/column hidden. Its annoying because I have to delete that section and add again to work with.

It happened with me as well.. tried to create blocks again and again.. But I think the problem is with "JETPACK". I deactivated jetpack and it worked.

**Comment by kushagra99** [comment]
> Simple solution//
> 
> If you the "JetPopUp" plugin, try deactivating it. If that's not the case, then try deactivating all plugins and turn them on one by one while testing your page until you identify which one does.
> 
> Good luck

It worked for me! 👍

**Comment by htmlswift** [comment]
I had the same issue and yes it was quite annoying , finally I fixed it by following the steps below -

1. Click on Edit Section
2. Select Advanced Tab
3. Go to Motion Effects
4. and Change the "Entrance Animation" to default.

Please note that if you are not using the Motion Effects, DO NOT SET the "Entrance Animation" to NONE. 
Instead it should be removed and set to default.

This way Elementor will not add ".elementor-invisible" to the section. 

Hope it helps!
Thanks!

**Comment by erosenin** [comment]
I updated my server php version to 7.2 from 5.6.4 and after that I had the same issue as everyon else here. 
Even with all plugins disabled it is not working correctly.
If I do the set animation to default the image carousel, sliders, h1s etc are not displaying correctly.

Please help!! :)

**Comment by htmlswift** [comment]
@erosenin can you send me your website url, where you are getting this error? so that i can take a look. thanks!

**Comment by 7k-media** [comment]
**@htmlswift Maybe I have this issue also...** 
Could you take a look at a page i'm doing for a client. I can't figure out why the small color images disappear whenever I'm activating one of the filters :( 

![elementor-acf-01](https://user-images.githubusercontent.com/69792597/90382194-b7a89000-e07e-11ea-9e8c-0f61339349e7.jpeg)
![elementor-acf-02](https://user-images.githubusercontent.com/69792597/90382208-bb3c1700-e07e-11ea-965e-8f77c8d1212e.jpeg)

https://bike-lease.dk/cykel/

Thank you for any help you can offer!

**Comment by htmlswift** [comment]
@7k-media will get back to you on this in a few minutes. thanks! :)

**Comment by htmlswift** [comment]
@7k-media Seems like, Issues are because of this Gallery Plugin - https://bike-lease.dk/wp-content/plugins/elementor/assets/lib/e-gallery/js/e-gallery.min.js When you select one of the filters, it removes the background image from the elements.

here is the video explaining the issue - https://www.loom.com/share/b6310ab3359d4497a482172a13c51416 that might help!

Let me know, what you think.
Thanks!

**Comment by 7k-media** [comment]
Thanks a bunch @htmlswift 
I changed to another gallery - and now it works  

#awesome #ioweyouacoffee 

![oweyou](https://user-images.githubusercontent.com/69792597/90450585-62a26380-e0ea-11ea-94dd-a05d2f22bb28.jpeg)

**Comment by htmlswift** [comment]
@7k-media Great! :) Happy to help! Cheers!

**Comment by skylarkyanci** [comment]
> Invisible content in Elementor is usually related to animations failing to load. The content begins hidden, an animation script is triggered, and they animate into visibility. The reason animations fail to load is usually because there is a javascript error on the page. You can right click -> inspect the page, and check the console to see what the error is. (It's the red text). If you do a bit of sleuthing, you can find where the error originates. In my case, it was a typed.js call on an widget that had an incorrect identifier. I removed the row with the bad widget and everything came back.

Thanks for the explanation

**Comment by worldoptimizer** [comment]
I am experiencing this too…

I had some `h2` in there that had an animation to appear with `fadeIn`… that suddenly stopped working. Brochure page no updates on content but on plugins and apart from Elementor Pro there is nothing on there.

I tried removing the animations… still hidden. 

I don't have the time to look into why this is happening on the page in question. It just is annoying as hell… I added custom CSS to the section for now:

```
selector h2 {
    visibility: visible !important;
}

```
🤦🏽‍♂️🤦🏼‍♀️🤷🏽

**Comment by htmlswift** [comment]
@worldoptimizer can you share the link where you are facing this? 
maybe I could take a look for you? thanks!

**Comment by RoninTai** [comment]
no se porque aparece y no se como sacarlo pero se como evitar por el momento. como es wordpress solo agrege en la opcion Apariencia -> personalizar -> css adicional 
 .elementor-invisible {
    visibility:visible;
}
y mis rows volvieron a aparecer.

**Comment by ibrahim-najjar** [comment]
Hello all,
I had the same problem.
but when I changed the slug of the translated pages to be the same as the original one, things appeared again.

**Comment by angeldavo** [comment]
Hello, I have the same problem.

Elementor adds me the elementor-invisible class when I add some animation to an element. But what I don't understand, is why it works on some pages and not on others.

**Comment by Youssef-Mhamdi** [comment]
Just want to add here if that helps, I was able to solve this issue for a client by checking his Elementor for that element ( in my case it was images )
I was able to fix it by disabling Zoom In option/animation, tested it on my test site and I was able to see that the .elementor-invisible only shows when you use responsive settings or animations in Elementor.

**Comment by angeldavo** [comment]
That's right. It's for adding animations.

But I want to use these animations. As I added the template based on a HOOK what I did in the end is to print a shortce and now it works fine for me.

**Comment by Youssef-Mhamdi** [comment]
Just want to add here if that helps, I was able to solve this issue by checking Elementor for that element ( in my case it was images )
I was able to fix it by disabling Zoom In option/animation, tested it on my test site and I was able to see that the .elementor-invisible only shows when you use responsive settings or animations in Elementor.

Hope this helps!
Cheers!

**Comment by Youssef-Mhamdi** [comment]
@angeldavo Nice work there ;) 
That can help as well

**Comment by jjdworks** [comment]
I found that the elementor-invisible class was being added to elements further down the page out of the initial viewport and therefore making these elements show up as empty blocks. This was resolved when I removed "height:100%;" from the body and html in CSS.

**Comment by peeyushkhandelwal** [comment]
Please add jquery-1.11.1.min.js in your header.php below the wp_head function

**Comment by angeldavo** [comment]
It still doesn't work even if I add jQuery in header.php

**Comment by yukirivero** [comment]
Fixed the issue, when your animations are on. Make sure to REMOVE "overflow: hidden, overflow-x: hidden, overflow-y: hidden" on the **html, body** tags and the holding containers of your elements

**Comment by angeldavo** [comment]
> Fixed the issue, when your animations are on. Make sure to REMOVE "overflow: hidden, overflow-x: hidden, overflow-y: hidden" on the **html, body** tags and the holding containers of your elements

Could you give an example of how to eliminate these classes?

**Comment by yukirivero** [comment]
not really want to eliminate the invisible class as it it is being used by Elementor for the animations.

you can set overflow: auto, overflow-x: auto on the body, or containers that hold your elements.

**Comment by yukirivero** [comment]
example: 
html{ overflow: auto !important; }

**Comment by amirshnll** [comment]
> Seems like same issue... (.elementor-invisible out of no where)
> `<div class="elementor-element elementor-element-6cfd343e animated-slow elementor-invisible elementor-widget elementor-widget-image" data-id="6cfd343e" data-element_type="widget" data-settings="{&quot;_animation&quot;:&quot;slideInDown&quot;}" data-widget_type="image.default"> <div class="elementor-widget-container"> <div class="elementor-image"> <img src="https://mh.site2go.co.il/wp-content/uploads/2019/04/MicroScope.png" class="attachment-full size-full" alt="" sizes="100vw" width="295" height="202"> </div> </div> </div>`
> Generated template with image that is using _slide in_ animation.
> How to regenerate:
> 
> 1. Keep some design with the above animation as template
> 2. Generate "single" builder template for posts - import the template from (1)
> 3. Replace static definition with dynamic (to apply to each post that meets the criteria)
>    Booom!
>    The image is not there anymore.
>    Tried to use "feature image" - no luck.
>    Now, I am stuck
>    :-)
> 
> Temporary _partial_ workaround: (animation is lost) - until solution is found
> Add class name to your post template say: "my-post-t"
> Add CSS:
> 
> ```
> .my-post-t .elementor-invisible{
>      visibility: visible;
> }
> ```
> 
> Ugly:
> 
> 1. Beware that Elementor may need this class on other cases
> 2. Its better then jQuery remove class! (I hate those JQuery "dancing" displays)
> 3. Animation is lost

work it

**Comment by mahofficial** [comment]
The issue is still not fixed. I am still having this issue with the latest version. I got this issue after using the latest version of new experiments. Before that everything was working fine.

**Comment by angeldavo** [comment]
The elementor plugin has become the plugin that should not be used, it puts a lot of crap which makes the web very very slow, so you have to look for other alternatives or layout the web bareback.

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v3.4.3

Feel free to update

Thanks!

**Comment by mahofficial** [comment]
> This issue has been resolved in Elementor v3.4.3
> 
> Feel free to update
> 
> Thanks!

Updated the plugin but it's not fixed!

**Comment by mahofficial** [comment]
On my side, it was a problem with elementor rendering SVG image after the update.

On my end, the SVG icon with the style attribute wasn't rendered correctly. Seems like the style attributes got sanitized causing every section to be in it and stopping animation from occurring. What I did is used presentation attributes instead of style attributes in my SVG icon and it fixed the issue.

Seems like the latest update of elementor got an issue with SVG icon rendering.

**Comment by seanvandermolen** [comment]
Still an issue on 3.4.3
https://staging.robbiekaye.com/gallery/paintings/a-new-day/


Setting min height on the section holding the image. Previous comment a user mentioned that was an issue for them. While the animation was nice, I can live without it or I'll recreate with pure css.  But odd to have to deal with it.

**Comment by DorShahar** [comment]
@mahofficial , @seanvandermolen  - thanks for reporting.
However, the problems you are describing have nothing to do with this specific fix. 
Please open a new issue, with steps to reproduce and system info so we could investigate it. 

Thanks

**Comment by xpertdigital** [comment]
I have found the solution.
I have disabled the "Improved Asset Loading" experiment and the issue got resolved.

**Comment by odin9den** [comment]
> **Fix for my case:**
> 
> I had a custom made widget, and one of the settings on the widget was named `animation` and this was tricking Elementor into thinking the object had an animation applied. So be careful naming your widget controls!

Thanks Michael! That was my case too, you saved my time :)

**Comment by Fydon** [comment]
Setting `Improved Asset Loading` to `Inactive` did not make a difference for me. `elementor-invisible` was still added. Setting `Entrance Animation` to `None` did cause it to display though. However this issue is not resolved. Should it not be reopened?

**Comment by MichaelPote** [comment]
> Setting `Entrance Animation` to `None` did cause it to display though.

That should be correct though - if there *is* a entrance animation, then the element should have `elementor-invisible` added on start before the animation plays.

**Comment by MuhammadArslanIshtiaq** [comment]
I had the same issue.
Problem:
When I enabled the Entrance Animation in Motion Effects of a section. the section would disapper on the frontend.
I checked the code with inspect element, elementor-invisible class was added, hence the element was not visible. 
I checked the console for errors,  there was one Uncaught TypeError with one of the js.min file.
Solution:
I was using WP-Optimize 3.2.19 plugin for the speed optimisation. From the plugin minify settings, I disabled **Process JavaScript files** option. Reloaded the site and the elements were now visible and animation was working fine.
Console error was also gone.

**Comment by vardumped** [comment]
The issue still occurs.
- Elementor: v3.19.2
- Elementor Pro: 3.19.2

I monitored the issue for a bit and the animation works fine in the Preview editor but not in the frontend. I do not get script loading errors and the .elementor-invisible class is set as originally mentioned by the bug ticket creator.
The bug is valid for Chrome, Firefox and Safari.

I don't use JavaScript or CSS minifier. 

I wrote this temporary solution in JavaScript. It checks if the element is at least 50% in the viewport and then removes the elementor-invisible class. The element is displayed, it's only set up to work with the fadeIn animation.

// Function to check if an element is in the viewport
function isInViewport(element) {
  var rect = element.getBoundingClientRect();
  var windowHeight = window.innerHeight || document.documentElement.clientHeight;

  // Check if at least 50% of the element is visible
  return (
    rect.top <= windowHeight * 0.50 &&
    rect.bottom >= 0 &&
    rect.left >= 0 &&
    rect.right <= (window.innerWidth || document.documentElement.clientWidth)
  );
}

// Function to toggle visibility class based on viewport
function toggleVisibility() {
  var elements = document.querySelectorAll('.elementor-invisible');
  elements.forEach(function (el) {
    if (isInViewport(el)) {
      if (el.classList.contains('elementor-invisible')) {
        el.classList.remove('elementor-invisible');
        el.classList.add('animate'); // Add CSS class for animation

        // Dynamically add CSS animation rules
        var style = document.createElement('style');
        style.textContent = `
          @keyframes fadeIn {
            from {
              opacity: 0;
            }
            to {
              opacity: 1;
            }
          }
          .animate {
            animation: fadeIn 0.5s ease;
          }
        `;
        document.head.appendChild(style);
      }
    }
  });
}


// Add event listener to scroll event
window.addEventListener('scroll', toggleVisibility);

// Initial check when page loads
toggleVisibility();

**Comment by AlviseC** [comment]
same error here with the last version of Elementor 3.20.3

i resolved creating a new section and migrating blocks from the old section

other solutions like change in default the animations or clear the cache don't help me

obviously, i cleared the cache after this changes

**Comment by rickscode** [comment]
How to fix.


1. Go to the page click edit with Elementor. 
2. Click element thats not appearing on front end anymore.
3. Click style tab then animation and if its turned off just it on and the element will be visible again.

**Comment by 0xagf0x** [comment]
Still running into this issue
