### ISSUE TITLE
Elementor 2.0.0 - Beta Release (Beta 4 UPDATED)

### ISSUE THREAD

**Issue by bainternet** [pojome/elementor#3706]
===========
## [Beta 4 UPDATED - PLEASE READ BELOW!](https://github.com/pojome/elementor/issues/3706#issuecomment-375440090)
===========

Hiya testers!

We are glad to present the first part of our theme builder: **Elementor v2.0.0**

**Please go over each new feature detailed below, and test it out on your own local website.**

This version **does not yet** include the extension beyond the page level, but we see it as a huge milestone that will set the stage for the next generation of our visual editor.

This version is the core for all the upcoming releases of Elementor 2.0, so stay tuned. We have a series of Elementor Pro releases planned, with countless improvements and new abilities coming your way.

## Blocks
Our design team have been working hard on this release for many weeks. Blocks are pre-designed section templates that can be easily combined to create a complete & beautiful website or landing page in minutes.

Click 'Add template' to open the library modal and choose the new Blocks tab. You get over 250 Blocks to start you off, spread across 15 different categories: CTA, hero, stats, contact and more. Blocks brings forth a new, more flexible workflow for creating websites.
<img width="450" alt="blocks-1" src="https://user-images.githubusercontent.com/660572/37153836-a8c89682-22e6-11e8-8773-70fe0014c42b.png">

## Document Type
We re-wrote the entire template code architecture, enabling us to develop new kinds of Elementor documents with elaborate settings and conditions.

For example, if you open a "Section" template, the document settings will not show the body style settings, just the setting for the content. This feature lets us introduce new types of documents to our editor like header or footer.

We also added a new template modal that pops up when you add a new template from the dashboard. Through this modal, you can choose the type of template you want to create (page or section) and give your template a name.

## Featured Image
We added the option to set a featured image through the document settings, thus removing the need to go back to the dashboard to set a featured image for a post. This feature is available for every CPT that supports featured images.
<img width="450" alt="document-setting" src="https://user-images.githubusercontent.com/660572/37153846-b0abb29e-22e6-11e8-90c3-db7522fed71c.png">

## Editor Tweaks
We reduced the 10% columns width limitation to 2%, allowing you to create a large number of narrow columns in each section. This is especially useful for areas like headers, where you might need to include several elements like logo, menu and search bar all in one row.

We also reduced the minimum height default settings for sections, to prevent display differences between preview and live mode.

## Developer Documentation
This version introduces a complete code reference for all of Elementor's PHP functions and classes. With this reference, you can get exact info regarding what every function does. It also including an elaborate documentation for all Elementor hooks.

In addition, we are in final steps releasing a complete area for developers, where you will be able to read tutorials on how to extend Elementor with new widgets and controls.

We’ll have updates concerning developer resources in the next few weeks, so stay tuned.

## Other improvements

- Tweak: Added inline view for icon-list widget
- Tweak: Match HTML tags for the section and the column
- Tweak: Slick.js v1.8.1 Updated
- Tweak: Updated eicons to v3.0
- Tweak: Updated select2 to v4.0.5

## What next?
In the next weeks, we'll be releasing a beta version for THE FULL Elementor Pro 2.0, where you will find the other pieces of the puzzle like header, footer and other theme building parts. Elementor Pro 2.0 beta will only work with Elementor 2.0 and above.

In the meantime we invite you to go through all the new features and test them out, making sure there are no conflicts with other plugins or themes. We'd really appreciate it if you make as many tests as possible, since this helps us release a much more stable version when we go out of beta.

### How to Install Beta Version
If you still haven't enabled beta testing in Elementor, please follow these steps:

1.  Go to Elementor > Tools > Versions
2. Enable the beta tester feature
3. Go to Dashboard > Updates and update to the latest beta version.

This will get you testing the new Elementor 2.0.0 Beta 4. You can also download the new version here: https://downloads.wordpress.org/plugin/elementor.2.0.0-beta4.zip

**Stable release**: March 20, 2018 (Estimated)

**Many thanks for your support and help!**

For bugs and remarks, please reply with a comment below!

[Elementor Beta - Sign Up Now For Our Elite Group Of Early Access Testers
](https://my.elementor.com/beta/)
Cheers,

**Comment by warcraft14115** [comment]
Please make a feature hide column. Sometime I need hide column on mobile.  Thanks

**Comment by Cyberdemon87** [comment]
Please consider adding functionality to show/hide elements based on the user role, like the Woorocks plugin.

**Comment by bainternet** [comment]
@Everyone 

Please keep this related to the Current beta Only! any other issue, feel free to open a new issue.

**Comment by Ver3** [comment]
Some buttons like > Document settings > Advanced > [Delete] break the design when in another language like Dutch. In that language "Delete" becomes "Verwijderen".

Possible solution: Ability to set Elementor in English even if the site in another language.

Currently, I set WP frontend to Dutch and admin to English. Sadly Elementor remains the language of the frontend. 

Hope this helps.

**Comment by jeff21up** [comment]
When inserting a block, if previewed first then insert, when you go to add another block the modal is stuck in the last section you viewed and none of the three nav buttons work
Jeff

**Comment by Jorihlen** [comment]
I'm having the same problem as jeff21up.
Work on local-by-flywheel-2-2-4-windows
WordPress 4.9.4 - PHP 5.6.20 - MySQL 5.6.34

**Comment by medvedbne** [comment]
Yep. can confirm this. On latest OceanWP (live)
When I use Insert button (top right) from Preview then it gets stuck. If i preview, then go back and insert that Block, all good.

**Comment by Basilou38** [comment]
1- there is a problem with the media carousel, the first and last picture overlaps. 
https://www.useloom.com/share/9f27ac2eafd346f59afcc9f01982029c

Can not not display an image with lightbox ?

2- "edit with elementor" does not work, the page does not load, you have to press the "enter" key to make the page load elementor.

**Comment by SencilloDS** [comment]
1) Jet Elements (1.8.0) breaks my site - the result after saving the page in Elementor is a white content in frontend.
2) In Dashboard (My library) I can select and create "page", "section" and "widget". When I select widget and it´s empty - there is a button "Create your first widget". But I can´t create a (global) widget, I only can create a new page or section. It would be nice to create a (global) widget in Dashboard, maybe also a global section?

**Comment by KiQdev** [comment]
So far everything I tested, and with a lot of other addons too, everything is perfect:-) Nice work, and a good plugin gets better and better:-)

**Comment by thejasonparker** [comment]
When I try to preview a page with the JetElements v1.8.0 plugin activated I get the following error...

```
Warning: Invalid argument supplied for foreach() in /app/public/wp-content/plugins/elementor/includes/base/controls-stack.php on line 1056 Fatal error: Uncaught TypeError: Argument 3 passed to Elementor\CSS_File::add_repeater_control_style_rules() must be of the type array, string given, called in /app/public/wp-content/plugins/elementor/includes/css-file/css-file.php on line 514 and defined in /app/public/wp-content/plugins/elementor/includes/css-file/css-file.php:768 Stack trace: #0 /app/public/wp-content/plugins/elementor/includes/css-file/css-file.php(514): Elementor\CSS_File->add_repeater_control_style_rules(Object(Elementor\Element_Section), Array, '', Array, Array) #1 /app/public/wp-content/plugins/elementor/includes/css-file/post-css-file.php(199): Elementor\CSS_File->add_controls_stack_style_rules(Object(Elementor\Element_Section), Array, Array, Array, Array) #2 /app/public/wp-content/plugins/elementor/includes/css-file/post-css-file.php(289): Elementor\Post_CSS_File->add_controls_stack_style_rules(Object(Elementor\Element_Section), Array, Array, Array, Array) #3 /app/public/wp-content/plugins/elementor/includes/css-file/post-css-file.php(158): Elem in /app/public/wp-content/plugins/elementor/includes/css-file/css-file.php on line 768
```

**Comment by silvioghedin** [comment]
the preview could not be loaded elementor

**Comment by daviedR** [comment]
BUG:

Autosaving procedure seems to have issue with selected theme's page template. Page template automatically switched to "Default Template".

**Comment by wangneo** [comment]
Insert "Hot Random Image" wediget to page will show "server error (400 bad request).
![400error](https://user-images.githubusercontent.com/16931779/37194519-8ab4514a-23a9-11e8-90c0-12a28d0b7d61.png)

**Comment by avermat** [comment]
I'm noticing that the Blocks have 0px left and right padding on desktop (left and right padding was only included for tablet and mobile). This causes a problem on some screen resolutions (the content runs to the edge of the section since there's no padding). And it's an even bigger issue if you happen to be using a wider "Content Width" than the default 1140px set in Elementor.

**Comment by isber-es** [comment]
When entering blocks, privisualize the design and insert it from that preview, when I try to add another template or block, the preview of the previous one appears and it does not allow to do anything. I have to refresh the page.
In the attached image, you see how the template option is selected, but only the preview is seen
![bloqueo-carga-plantillas](https://user-images.githubusercontent.com/37208861/37201930-634524c4-2389-11e8-95a7-661761f2e06f.png)

**Comment by isber-es** [comment]
When you add a highlighted image and save, the highlighted image does not appear, you must reload the page.

**Comment by mgpub** [comment]
template selection is not working at all.
when i click ADD TEMPLATE I only get 1 block displayed. This same block is shown for all 3 tabs: Blocks, Pages and My Templates.
No other templates are shown or are accessible.

**Comment by cstibi** [comment]
At his moment you have to click to preview a selected blocks. If you do not like it you click "Back to Libray" which not going back to the actual block but at the first block. Maybe it will be better to show block and page preview when 2 secs hovered. What do you think about it?

**Comment by Manuel-SG** [comment]
Having the same issue:
_When inserting a block, if previewed first then insert,  when you go to add another block the modal is stuck in the last section  you viewed and none of the three nav buttons work_
ASTRA THEME, WP4.9.4 no other plugins apart from Elementor 2 beta1

**Comment by badcat** [comment]
Suggestion for adding a Dark/Light Filter or Tag for Blocks

**Comment by miekevanzachts** [comment]
I can only insert one block and there after I won't be able to insert another one, because it won't work anymore. keep on seeing the same block and can't insert a template eighter. I use GP premium 1.6 beta theme and wp 4.9.4.

**Comment by KiQdev** [comment]
Same problem with the blocks as others.

**Comment by ElleChesnoiu** [comment]
Having the same issue:
When inserting a block, if previewed first then insert, when you go to add another block the modal is stuck in the last section you viewed and none of the three nav buttons (blocks, pages, my templates) work.
A page refresh fixed it for me once. Latest official releases of GP + GP premium and no other plugins except Elementor (beta) and Elementor Pro.

**Comment by MayaNikolova** [comment]
Hi. It seems like a button liked to an anchor is not going to the anchor location when pressed. 

https://www.naturevolution.net > button 'Our World' does not scroll to https://www.naturevolution.net/#underhero 

Also when hovering over the button itself, the right-hand border changes width...

Cheers
Maya

**Comment by norewp** [comment]
With WP_Debug set to true I get the following PHP NOTICE

Notice: Array to string conversion in C:\xxxx\xxxx\www\http\wp-content\plugins\elementor\core\dynamic-tags\manager.php on line 35

**Comment by bainternet** [comment]
@Ver3 
Thanks for reporting fix: https://github.com/arielk/elementor/commit/4cef06438155c7bc98a63dcde8e0bbc3ddbbd262

@jeff21up @Jorihlen @medvedbne @isber-es @Manuel-SG @miekevanzachts @KiQdev @ElleChesnoiu 
thanks for reporting fix: https://github.com/kobizz/elementor/commit/63b5d86c0744e31c16b456e9eb67af7a35969241

@MayaNikolova @mgpub @Basilou38 
thanks for reporting, this seems unrelated to the current beta, can you confirm if the issue persists on stable version? if not please open a new issue.

@badcat 
Thanks for the suggestion, we are thinking about adding Drak/Light tags.

@cstibi 
We do have some thought about it here, not sure what will happen in the end but it is something that's on our minds.

@wangneo @thejasonparker @SencilloDS @isber-es 
Thanks for reporting, but there is nothing we can do to fix it, the fix needs to come from the 3rd party plugins.


@avermat 
The blocks are meant as a quick start/wireframing templates, you can change the styling ( including the padding ) to fit your needs.

@norewp 
thanks for reporting, can you provide steps to replicate, and lets continue this issue here https://github.com/pojome/elementor/issues/3718

Thanks, everyone,  keeps them coming.

**Comment by MayaNikolova** [comment]
Hi again,

Tried the button on 2.0, still not scrolling to anchor.

I rolled back to the previous Elementor version 1.9.7 and the button is now working correctly. You can watch the video file attached. No other changes have been made except the roll back to 1.9.7.

[1.9.7.zip](https://github.com/pojome/elementor/files/1800187/1.9.7.zip)

Have re-installed 2.0 and the button does not work once again. 
Website currently on 2.0, can access below:

https://www.naturevolution.net > button 'Our World'  scroll to https://www.naturevolution.net/#underhero

I would say it is related to 2.0...unless there is a conflict with another plugin that works fine with 1.9.7.

Maya

**Comment by HikmetSener** [comment]
Great updates thanks, some the stuck problems are already mentioned. What I would suggest is to add a next and prev button on the blocks navigation to be able to preview the next block. Now we have to go back to the list and choose a template block each time. 

Thanks,
Hikmet

**Comment by swancott** [comment]
== Environment ==
WordPress 4.9.4 (Fresh Install)
GeneratePress / GP Premium 2.0.1.1514662723
BuddyPress 2.9.3
Elementor - 2.0.0-beta1

== Issue ==
BuddyPress adds a notrification icon next to the user name:

![beta_buddypress](https://user-images.githubusercontent.com/13833853/37253212-04c43bb0-2505-11e8-80c1-2a9710de78f5.png)

When clicking on this notification icon the following error is given:

![beta_buddypress_2](https://user-images.githubusercontent.com/13833853/37253309-74d618d2-2506-11e8-93ec-fa6ecf81b935.png)

This same configuration using Elementor 1.9.7 works as expected

**Comment by bainternet** [comment]
@MayaNikolova 

Seems more of an issue with the anchor rather than the button. In the page you linked, there is no anchor with the name "underhero". can you confirm?

**Comment by drank** [comment]
@MayaNikolova, I also checked and can confirm @bainternet's finding - there is no element with ID "underhero" (view the source of the page in the browser and see for yourself) and therefore there is nowhere for the button to go to when clicked.

**Comment by KiQdev** [comment]
@MayaNikolova Noticed the same. The anchor don´t work now. Put it in CSS ID and see if that solves it.

**Comment by MayaNikolova** [comment]
Hi there, have done some more testing to try and isolate the issue. It seems like the issue is with the anchor div. On inspect you can see that in 2.0 the div id is missing. When rolling back to 1.9.7 the div id="underhero" is there. Screenshots attached of code in each version and also the anchor widget in Edit page.
Cheers
Maya
[Html 2.0 vs. 1.9.7.docx](https://github.com/pojome/elementor/files/1800866/Html.2.0.vs.1.9.7.docx)

**Comment by avermat** [comment]
@bainternet I realize these are meant to be a quick start, however, there are a lot of use cases where not having desktop padding will cause problems. For example:

1) What if my page has a sidebar?
2) What if I'm using a narrow blog layout like you use on elementor.com?
3) What if I'm using a boxed layout that popular themes have, like Astra?
4) What if I re-size my browser window to somewhere between 1024-1140px?

In all of these examples, there won't be any left and right padding. Adding left and right padding to the sections would fool-proof these layouts more and ensure they aren't messed up by the user's theme settings, elementor width settings, etc.

![oceanwp](https://user-images.githubusercontent.com/29379115/37264238-3953339e-25e7-11e8-8961-00749de64c20.png)

![astra-boxed](https://user-images.githubusercontent.com/29379115/37264241-3e2c506c-25e7-11e8-81bd-31a22fc7d8bb.png)

![1024-1140viewport](https://user-images.githubusercontent.com/29379115/37264231-34026ef0-25e7-11e8-8497-652fb3e3e8b1.png)

**Comment by dudaster** [comment]
@MayaNikolova is right. The anchor ID isn't in the html source. It is easy to reproduce. It must be fixed.

**Comment by donwattz1459** [comment]
In the Library section when clicking add new, there is no "Widget" option but if I navigate to the Wdiget tab in the Library, I can create a new one there. I think there should be a widget dropdown in the "Add new" popup.

**Comment by donwattz1459** [comment]
![screenshot at mar 12 11-23-03](https://user-images.githubusercontent.com/16137152/37292691-ccccadd0-25e7-11e8-858d-545dff62627a.png)

**Comment by mgpub** [comment]
Hi, no change has appeared. the issue with Blocks not working is still readily apparent.

When viewing a possible Block to see what it is like, if I then cancel out of the window ( clicking X), once I reenter the ADD TEMPLATE popup, the previously viewed block is shown for all 3 tabs: Blocks, Pages and My Templates.
No other templates are shown or are accessible.

**Comment by mgpub** [comment]
Has there been an update to the Beta yet?
I am not seeing any available updates and I am still on Version 2.0.0-beta1 
I am curious why @bainternet is asking for existing confirmation of issues???

**Comment by comput3rguy** [comment]
![block_mobile_column_width](https://user-images.githubusercontent.com/25492570/37310663-09ce1e66-261b-11e8-9ada-b327fb8026db.jpg)
Hi,

I added a service block with 4 columns when I change the width to 50 for mobile so two columns show side by side instead of stack, the 2nd column does not align with the first column.

I was following Cassie's video for creating mobile responsive columns:
https://youtu.be/VPyBuNLpt4U?t=2m10s

Using Astro Pro Theme & the following:
Active Plugins |   |  
-- | -- | --
Astra Pro - 1.2.0 | By Brainstorm Force |  
Customizer Search - 1.1.2 | By Brainstorm Force |  
Duplicate Post - 3.2.1 | By Enrico Battocchi |  
Elementor - 2.0.0-beta1 | By Elementor.com |  
Elementor Pro - 1.15.3 | By Elementor.com

**Comment by avermat** [comment]
@comput3rguy It's because there was padding added to the top of the second column, but not the first column (if you remove the padding from the top of the second column they will line up). 

Their blocks don't use uniform padding in columns so you have to be careful when adding/removing columns or adjusting column widths.

**Comment by bainternet** [comment]
@comput3rguy 
@avermat  is correct if you when you play with the block layout you need to make sure the style matches your changes.


@avermat 
I have notified our block designers to keep in mind the padding.

@mgpub 
No update yet. One should be out, in the next day or two. 
As for the confirmation request, read again, it was for a different issue reported.

And again, thanks everyone for the feedback.

**Comment by bainternet** [comment]
# v2.0 Beta Version Beta 2

We just released a new beta version, please update your version to v2.0.0 Beta 2.
https://downloads.wordpress.org/plugin/elementor.2.0.0-beta2.zip

This beta release includes:

- New: Added new page templates: Elementor Header & Footer
- Tweak: Remember the last library tab and search/filters that was open
- Tweak: Updated the way widget categories are registered in Elementor
- Fix: Preview gets stuck after closing templates modal (Thanks @jeff21up)
- Fix: Changed button style in the control panel to handle with various languages (Thanks @Ver3)
- Fix: Print editor placeholder only if for the current edited post (#3671)
- Fix: Color picker style for RTL mode
- Fix: Responsive width for Select2
- Fix: Allow check is_preview per post id to support multiple edit areas in the editor
- Fix: Removed new widget button type from My Templates (Thanks @SencilloDS)

For bugs, feedback and remarks, please reply with a comment below!

Please keep this related to the Current beta Only! any other issue, feel free to open a new issue.

Thanks again to everyone.

**Comment by comput3rguy** [comment]
@bainternet Did something changed with the download link?

This site can’t be reached
The webpage at https://downloads.wordpress.org/plugin/elementor.2.0.0-beta2.zip might be temporarily down or it may have moved permanently to a new web address.
ERR_INVALID_RESPONSE

**Comment by KiQdev** [comment]
The update fails, and the link for download isn´t working for beta 2

**Comment by mgpub** [comment]
Updated to Beta2:
Previously reported issue with adding an existing Block Template still exists but is now worse.

When viewing a possible Block to see what it is like, if I then cancel out of the window ( clicking X), once I reenter the ADD TEMPLATE popup, the previously viewed block is shown for all 3 tabs: Blocks, Pages and My Templates.
No other templates are shown or are accessible.

New Issue:
The Block Preview is contained in a very short window with scroll bars. Makes viewing the Block in preview nearly impossible.

**Comment by avermat** [comment]
I'm unable to find the Header/Footer templates in beta2. I looked under Blocks, Pages, checked the categories, and also tried searching for them. Am I missing something here?

**Comment by SencilloDS** [comment]
I have the same problem like "avermat". No Header/Footer templates in beta2.

**Comment by KiQdev** [comment]
Preview of blocks  works perfect for me now.
Header-footer templates are missing

tis 13 mars 2018 kl 13:53 skrev SencilloDS <notifications@github.com>:

**Comment by bainternet** [comment]
@comput3rguy , @KiQdev 
Link fixed.

@avermat , @SencilloDS 
Elementor Header & Footer It a new "page template" not something you import from the library.
Something more of a light version of the infamous "Canvas" with the current theme header and footer only. Head over to Document Settings >> Template, and you should see it in the drop down.

@mgpub 
We can't replicate the issue you are describing, can you clear server/browser cache? test on a different environment? deactivate other plugins? switch theme? steps to replicate? so we could get an idea of what you are talking about.

**Comment by avermat** [comment]
@bainternet Ah I see now, thank you :)

**Comment by eliasandersen** [comment]
How do I change my pages featured image using elementor?

**Comment by Manuel-SG** [comment]
Ok, the "persistent block" issue is gone now :-)

**Comment by CursiveQ** [comment]
Issue: Button widget "Hover" settings - Choosing color picker for text color and background color shows Hover Animation dropdown on top of it, blocking the color picker slightly.

Also happens with Icon widget in the Icon Hover settings and choosing Primary Color.

- Elementor 2.0.0 beta2
- OceanWP
- No other plugins installed
- Chrome & Safari

**Comment by mgpub** [comment]
@bainternet After deactivating all other plugins the issue was gone.
I then reactivate all plugins and it is now working just fine - so no idea why this was happening to some of us???

**Comment by KiQdev** [comment]
The anchor widget still not working in beta 2, you must put it in CSS ID to make it work

**Comment by KiQdev** [comment]
With Beta 2 version 2 I get 500 error on all sites if  i try to import a template

**Comment by tscheipi** [comment]
I don´t understand how to work with template header/footer - what is it for?

**Comment by iCoachLive** [comment]
Header footer-You put your own styles from the My Templates. But does the header stay sticky like it does with my theme? Otherwise, why would I switch?

**Comment by comput3rguy** [comment]
![unable_to_move_sections](https://user-images.githubusercontent.com/25492570/37368113-a9e93f32-26db-11e8-9777-15441d50954a.jpg)
@bainternet Updated to Beta 2, I am unable to move sections, up and down, I have was beta 1, tested with blocks, pre-built templates and just adding new sections.

Using Astro Pro Theme & the following:

Active Plugins |   |  
-- | -- | --
Astra Pro - 1.2.0 | By Brainstorm Force |  
Customizer Search - 1.1.2 | By Brainstorm Force |  
Duplicate Post - 3.2.1 | By Enrico Battocchi |  
Elementor - 2.0.0-beta2 | By Elementor.com |  
Elementor Pro - 1.15.3 | By Elementor.com

**Comment by dfuytn** [comment]
Just wanted to verify what others are saying about the anchor not working in Beta2

**Comment by ravilrrr** [comment]
Where it is now?
![2018-03-14_08-36-04 2](https://user-images.githubusercontent.com/5197026/37383597-0f7e6638-2763-11e8-8e50-712cafeea1cb.png)

**Comment by tudormnt** [comment]
I can confirm what @daviedR reported. Pages that currently have a template set - Elementor Canvas -
 revert back to the default template but the actual setting (both in wordpress and the editor panel) remains "Elementor Canvas".

Moreover, seems like pages pages that ARE currently published, once opened with Elementor, get the message "This is just a draft ... " and the field with the name of the page inside document settings changes to "Auto Save ...". Needless to say that when updating, the name of the page changes to that as well.

![screen shot 2018-03-14 at 09 12 38](https://user-images.githubusercontent.com/3028412/37388183-19ad4264-2768-11e8-9adb-8fa2f66b48f9.png)
![screen shot 2018-03-14 at 09 12 45](https://user-images.githubusercontent.com/3028412/37388184-19ce5d0a-2768-11e8-8fa3-1060f35356d9.png)

This happens immediately after updating to 2.0-Beta2 and I didn't test it on the first beta. This issue might have an effect on all websites that run Elementor as templates and statuses will change inadvertently.

**Comment by Manuel-SG** [comment]
Yes, in beta 2 the anchor ID does not exist. Here is an example: https://pager.demo.site/test/
The button on top has the anchor link "someanchor".
At the end of the page there is the an anchor menu widget with "someanchor". But the ID is missing. If you look in the source code you find the element just "empty".

That is a serious bug. Please fix ASAP.

**Comment by Alimzhan3** [comment]
Please, get rid of children's illnesses, - the tag "the sea" still does not work for you! This is very bad!

**Comment by TerenceMilbourn** [comment]
What an awesome update guys!!!  

And the "Blocks" feature is exactly what I wanted.

Great job!

**Comment by SencilloDS** [comment]
Beta2 and Element Theme. After open Elementor edit-mode header and footer are shown in a terrible way.
![schnappschuss__001](https://user-images.githubusercontent.com/37189694/37414323-223547e2-27a9-11e8-8201-d5357d13996a.png)

**Comment by forcedlogic** [comment]
Maybe I am being slow but whats the purpose of a page that includes a header and footer? Doesn't the default Wordpress page contain that? Am I missing something, why would I use a header/footer page rather than the default?

**Comment by Manuel-SG** [comment]
@SencilloDS : You are using the "granular addon", right? So try again without. 
@forcedlogic : Please keep this to bugs only, not starting a "why is that" discussion - that would be done more appropriate in the Facebook group :-)

**Comment by daviedR** [comment]
Please use Font Awesome 5 for version 2.0.0

**Comment by bainternet** [comment]
@mgpub 
You are the only one reporting this, and if it's gone after deactivating/reactivating plugins, could be cache related issue.

@KiQdev, @dfuytn, @Manuel-SG 
Ok, we replicated the anchor issue and it should be fixed in beta3. ref: https://github.com/kobizz/elementor/commit/a83cd9bce8478722f7bdf61c32552ac7ea280b8a

@KiQdev,
As for the import, is it from a local file, or from Elementor library of templates? if its a local, can you send us the template and will take a look?

@tscheipi, @forcedlogic 
Same as "canvas" but with your theme's header and footer, the main idea behind it is that you get a full-width layout, no sidebars, etc...

@ravilrrr
If your post type supports excerpts then it should be there in the same place.

@tudormnt 
We can't replicate the template issue, can you provide steps to produce issue?
As for the autosave issue: same, we need steps to replicate and did you jump version from 1.8.X to this beta? We do have some Idea what happens here but need more data.

 @SencilloDS 
Same as before any issues with 3rd party themes/plugins should be reported to them, we have no control over them.

Please keep this issue for beta related bug/issues only, for any questions, requests or none related issues please feel free to open a new issue.

Thanks again everyone for helping out.

**Comment by KiQdev** [comment]
The 500 error I get is when trying to import a local file. I will send one
of the files to you.

tors 15 mars 2018 kl 09:50 skrev raz ohad <notifications@github.com>:

**Comment by SencilloDS** [comment]
forcedlogic: I´m using Granular, but the problem is also without Granular Controls Plugin. I think the problem is with element theme. I tried it out with another theme and I had no such a problem.

**Comment by KiQdev** [comment]
Sent the requested json file to support so you can check it

tors 15 mars 2018 kl 10:12 skrev SencilloDS <notifications@github.com>:

**Comment by pingram3541** [comment]
Love the new "Blocks" feature!  Would be great to have some header/footer blocks too!

Would be great if the new dev docs explained a way for us to provide our own block libraries where we can provide blocks matching our own style guides, i.e. modern, flat, minimal, light, dark etc

**Comment by daviedR** [comment]
@bainternet Please fix the Page Template issue.

When on Editor, and you try to change the Page Template from the Editor. The preview shows correct page template, but the class on the preview's `<body>` still has `page-template-default` and it doesn't save into DB (doesn't update the `_wp_page_template` post meta).

**Comment by daviedR** [comment]
Looks like it only update the post revision `_wp_page_template` post meta. But in frontend, WordPress seems to use main post `_wp_page_template` post meta.

**Comment by pingram3541** [comment]
Testing on FastComet, back in 1.9.8 changing page templates is ok, in 2.0 changing page templates result in a 403 with admin-ajax.php as well

**Comment by pingram3541** [comment]
Something must have changed with the ajax call because a previous template I had used an html element with the following script:

```
<script>
(function($){
    $('body').find('#gallery-1 .gallery-icon a').attr('rel','prettyphoto[gallery-1]');
})(jQuery);
</script>
```

and saving using the previous 'stable' version it saves no problem.  However when editing in 2.0 if this element is present the page will not save and an admin-ajax.php 403 error is displayed.

I don't use this method on live sites, typically just on templates I provide to the public so that the needed custom script code is also packed up in the json file for import/export purposes.

**Comment by bainternet** [comment]
@pingram3541 

We can't replicate,  and 403 could be caused by apache mod security, can you provide steps to replicate and environment info, please?

**Comment by pingram3541** [comment]
Using FastComet SpeedUp hosting plan, modsec/caching disabled. Steps to reproduce...

1) Create new page and edit with Elementor
2) Add an HTML element - save = ok
3) Add <script></script> tags and try to save - 403

4) Roll back Elementor version
5) Repeats steps 1-3 and saved = ok
				
```
== Server Environment ==
	Software: Apache
	MySQL version: 5.6.38
	PHP Version: 7.0.28
	PHP Max Input Vars: 4000
	PHP Max Post Size: 256M
	GD Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.9.4
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 256M
	Debug Mode: Active

== Theme ==
	Name: Astra Child
	Version: 1.2.5

== Active Plugins ==
	Elementor
		Version: 2.0.0-beta2
		Author: Elementor.com

	Elementor Pro
		Version: 1.15.3
		Author: Elementor.com

== Debug ==
	Errors: 
		TypeError: Cannot read property 'html' of undefined
			at https://mysite/wp-content/plugins/elementor/assets/js/editor.min.js - 2:79295
			2018-03-17 21:25 +00:00

		TypeError: Cannot read property 'html' of undefined
			at https://mysite/wp-content/plugins/elementor/assets/js/editor.min.js - 2:65467
			2018-02-22 08:20 +00:00

		TypeError: Cannot read property 'errors' of undefined
			at https://mysite/wp-content/plugins/elementor/assets/js/editor.min.js - 2:114367
			2018-02-22 08:05 +00:00
			x 20 times
```

**Comment by pingram3541** [comment]
Hmmm, ok just setup another site on same exact plan, same theme and it is NOT displaying the same symptoms, reaching out to the host, maybe they have some kind of hidden mu-plugin they installed.

**Comment by norewp** [comment]
@SencilloDS Can you DM with the issue you having with Element Theme together with as much info as possible to replicate it. I'll get a fix out as soon as I know the cause.

**Comment by parfilov** [comment]
Hello. Please check out the translation strings. There are some non translatable. I can make a report if you need.

**Comment by pulla** [comment]
Hello, same as here ( Beta 2 )
We are using Elementor in BuddyPress themes.

Buddypress pages are not loading cuz of this error. If 2.0 is released, then all of the users will not able to use it.  Can you please have a look and fix?

`Fatal error: Uncaught Error: Call to a member function get_meta() on boolean in \htdocs\wp-content\plugins\elementor\core\settings\page\manager.php:132 Stack trace: #0 \htdocs\wp-includes\class-wp-hook.php(286): Elementor\Core\Settings\Page\Manager->template_include('C:\\Bitnami\\wamp...') #1 \htdocs\wp-includes\plugin.php(203): WP_Hook->apply_filters('C:\\Bitnami\\wamp...', Array) #2 \htdocs\wp-includes\template-loader.php(73): apply_filters('template_includ...', 'C:\\Bitnami\\wamp...') #3 \htdocs\wp-blog-header.php(19): require_once('C:\\Bitnami\\wamp...') #4 \htdocs\index.php(17): require('C:\\Bitnami\\wamp...') #5 {main} thrown in \htdocs\wp-content\plugins\elementor\core\settings\page\manager.php on line 132
`

Thank you for great plugin!

**Comment by stllrnet** [comment]
Would be awesome to have an option on Blocks that prevents the download of assets, so you don't end up having unnecessary files on your storage. This would be useful for production sites that want to benefit with the new features but don't want needless images into their servers.

**Comment by wangneo** [comment]
Hello,
When I use elementor woocommerce product widget, and use Oceanwp theme, the product will become duplicate, please check:
[http://nimb.ws/HFqKk4](http://nimb.ws/HFqKk4)
I has ask Oceanwp, they say WooCommerce css is not taken into account, and they need me to ask you the direction to fix it. 
Please let us know what can be the issue, why WooCommerce css is not taken into account.and please send me to the right direction.

**Comment by pulla** [comment]
Hello, 
I am sorry to bother you. But get_meta in BuddyPress issue should be fixed before it released.
If not, all of BuddyPress users won't be able to use V2.0. 

Thank you for the great plugin.

**Comment by bainternet** [comment]
@pulla, @swancott 

BuddyPress issue should be fixed in next Beta.

**Comment by bainternet** [comment]
# v2.0 Beta Version Beta 3

We just released a new beta version, please update your version to v2.0.0 Beta 3.
https://downloads.wordpress.org/plugin/elementor.2.0.0-beta3.zip

This beta release includes:

- Tweak: Dropped Support WP 4.5, so only 4.6 and higher.
- Tweak: New settings interface for role manager.
- Fix: Icon Box widget handling cases when no icon is set.
- Fix: Anchor Menu widget conflict (Thanks, @MayaNikolova, @KiQdev, @dudaster, @dfuytn, @Manuel-SG).
- Tweak: Renamed "Elementor Header & Footer" as "Elementor Full Width".
- Fix: Virtual pages overwriting global query ( BuddyPress issue, Thanks, @pulla, @swancott).
- Fix: Remove `margin-top` when multiple templates are loaded in the editor.

For bugs, feedback and remarks, please reply with a comment below!

Please keep this related to the Current beta Only! any other issue, feel free to open a new issue.

And Keep an eye for [Elementor Pro 2.0.0 Beta](https://github.com/pojome/elementor/issues/3826) that should be out in a few minutes.
Thanks again to everyone.

**Comment by pulla** [comment]
Thank you for your update.

The previous buddypress issue has been solved. Thank you.

But there is one more error with buddypress.

`Fatal error: 
Uncaught Error: Call to a member function get_controls() on boolean in C:\...............wp-content\plugins\elementor\core\settings\page\model.php:165 Stack trace: 
#0 C:\...............wp-content\plugins\elementor\includes\base\controls-stack.php(1822): Elementor\Core\Settings\Page\Model->_register_controls() 
#1 C:\...............wp-content\plugins\elementor\includes\base\controls-stack.php(461): Elementor\Controls_Stack->init_controls() 
#2 C:\...............wp-content\plugins\elementor\includes\base\controls-stack.php(265): Elementor\Controls_Stack->get_stack() 
#3 C:\...............wp-content\plugins\elementor\includes\base\controls-stack.php(1707): Elementor\Controls_Stack->get_controls() 
#4 C:\...............wp-content\plugins\elementor\includes\base\controls-stack.php(1836): Elementor\Controls_Stack->sanitize_initial_data(Array) 
#5 C:\Bitnami\wam in C:\...............wp-content\plugins\elementor\core\settings\page\model.php on line 165
`

Thank you.

**Comment by momo-fr** [comment]
In some cases, if I try an expanded section, the content disappears completely.

**Comment by ThrudUK** [comment]
Not sure if this has been mentioned but when trying to add a header using Pro and normal Astra I get the preview cannot be loaded screen that you see here. https://docs.elementor.com/article/245-preview-could-not-be-loaded?utm_source=editor-panel&utm_medium=wp-dash&utm_campaign=learn

Switch Generate Press and everything works.

**Comment by Artneo7** [comment]
While editing in Elementor the font (Varela Round) is appearing and fine. When viewing the live version, only the sans-serif font is showing, even with the Varela Round selected. Before updating to 2.0 this wasn't happening.
![error](https://user-images.githubusercontent.com/17693529/37728899-40598906-2d1a-11e8-860e-af3c30f605f4.png)
Hope to help if this is some kind of bug.
Thanks a lot! Loving Elementor 2.0! ❤👨‍💻

**Comment by Artneo7** [comment]
Also, I realized the "Post Archives" module doesn't have support for the badge design and the box shadow effect isn't working.
![error](https://user-images.githubusercontent.com/17693529/37739930-9375030c-2d3a-11e8-926c-656feb4927a3.png)

**Comment by JoeKrenek** [comment]
Hi,
editing on my primary device works only sometimes (screenshot). I tried deleting cache, incognito mode, disabling cache, Chrome, Opera, FireFox browser but nothing.

The problem was here before 2.0 update - now i have elementor Version 2.0.0-beta3 & elementor pro Version 2.0.0-beta1 and still the same.

Strange is, that it is working on my mobile & work laptop. I have Surface Pro 3 with latest updates.

I tried deleting plugins, changing theme, change settings,.. just everything but i don´t know what to do next and i would really love to work on my websites from my personal laptop.

www.new.jkrenek.cz


![capture](https://user-images.githubusercontent.com/37343145/37741152-92cfa800-2d60-11e8-9adb-da9c32880d18.PNG)

**Comment by eltonb** [comment]
JetBlog for Elementor Smart Posts Tiles causes the following error;

Warning
: Invalid argument supplied for foreach() in
C:\xampp\htdocs\wordpress\wp-content\plugins\elementor\includes\base\controls-stack.php
on line
1714

Warning
: Invalid argument supplied for foreach() in
C:\xampp\htdocs\wordpress\wp-content\plugins\elementor\includes\base\controls-stack.php
on line
1714

* It's probably an issue with the JetBlog for Elementor plugin, but I thought I'd report it anyway.

**Comment by KiQdev** [comment]
Testing with Elementor Hello theme
1. Box shadow for archive widget don´t display.
2. Saving a section says error under conditions button, and the Save without conditions button is greyed out
(3. Same as before in beta 2. Some templates gives 500 error when trying to import them, most works. )

**Comment by bainternet** [comment]
@pulla 
Thanks we will look into it.

@ThrudUK 
we cant replicate, can you please try to turn on WP_DEBUG and see if you are getting any server side errors, add to your wp-config.php :
```
define( 'WP_DEBUG', true );
define( 'WP_DEBUG_DISPLAY', true );
```

@JoeKrenek
If the problem was there before, then it's not related to this beta, please feel free to open a new issue and we'll try to help you out.

@eltonb 
Any issue with 3rd party plugin should be reposted to them as we have no control over them.

@momo-fr , @Artneo7 , @KiQdev 
Any Elementor pro issue should be reported in the [Pro 2 beta thread](https://github.com/pojome/elementor/issues/3826)
No need to re-post there but just the help organize things, next time report Pro related issues there.

@KiQdev 
We are still testing out the template you've sent us.

Thanks everyone,

**Comment by ThrudUK** [comment]
@bainternet 

Did as you suggest but not sure what is meant to happen when I add that debug info.

Still seeing the same problem.

In the console I am seeing : 
<link rel=preload> must have a valid `as` value 
Which links to :
/wp-admin/post.php?post=27&action=elementor#library

**Comment by ThrudUK** [comment]
@bainternet 

Done some more testing.  Seems to be a conflict with 

https://wordpress.org/plugins/wp-retina-2x/

**Comment by bainternet** [comment]
# v2.0 Beta Version Beta 4

We just released a new beta version, please update your version to v2.0.0 Beta 4.
https://downloads.wordpress.org/plugin/elementor.2.0.0-beta4.zip

This beta release includes:

- Tweak: Reintroduce divider control for UI panel (Developer API)
- Fix: Fonts not loading external templates in the editor preview
- Fix: Template stuck on draft status on publish

For bugs, feedback and remarks, please reply with a comment below!

Please keep this related to the Current beta Only! any other issue, feel free to open a new issue.

And try out our [Elementor Pro 2.0.0 Beta](https://github.com/pojome/elementor/issues/3826) as well

Thanks again to everyone.

**Comment by woodswork** [comment]
Updated to beta4 and tried to export a template. Got this error: {"success":false,"data":"Post ID is required."} That's on Astra with only E2beta4 and EPro2beta1 activated.

**Comment by wangneo** [comment]
Same as woodswork, using OceanWP, now is back to E2beta3

**Comment by KiQdev** [comment]
Same here when importing a template. {"success":false,"data":"Post ID is
required."}

fre 23 mars 2018 kl 08:53 skrev wangneo <notifications@github.com>:

**Comment by Basilou38** [comment]
@bainternet 

Hi

I have a problem with the contact form, I get an error message (see screenshot) after submitting the form. I tried to disable my cache plugin and remove the captcha field, same problem. An idea ? (I use the beta version of elementor)

screenshot of the error:
[http://zupimages.net/viewer.php?id=18/12/too2.jpg]

**Comment by Aljook** [comment]
Hi ,

First comment on any GitHub anything. 

BUG: I made a custom header with black background. Then after a while I changed the background color. All changes appear on live, however when I edit eg Home page in Elementor, it still shows the header with black background.

I have tried everything related to cache, hard refresh, etc. Nothing seems to work.

Cheers,

Alo

**Comment by donwattz1459** [comment]
Same error: {"success":false,"data":"Post ID is required."}

Astra and EPro

**Comment by donwattz1459** [comment]
I am trying the new feature "Preview as" under the eyeball next to update but when i choose to preview a page that is set up and have the template "Elementor Fullwidth" it does not seem to show me the page content.

**Comment by donwattz1459** [comment]
Is there going to be a way to make the section background image dynamic like the image element? That would be awesome!

**Comment by pulla** [comment]
Hello again,

Any news for this issue I posted up there?

Fatal error: Uncaught Error: Call to a member function get_controls() on boolean in C:\...............wp-content\plugins\elementor\core\settings\page\model.php:165

Thank you!

**Comment by nickdgreen** [comment]
Elementor 2 beta 4, Pro beta 1
Menu Element used in the Blocks Header: The drop-down hover background colour is not constrained by the border setting where a border radius is set.
![settings](https://user-images.githubusercontent.com/22448787/37877693-ca9b5952-3056-11e8-90cf-eb3f1ac3c3e6.png)
![menu-dropdown](https://user-images.githubusercontent.com/22448787/37877697-d31edc02-3056-11e8-8b4f-f25fb053d4c4.jpg)

Why is there no ability to set a radius on the top level Main menu items?

**Comment by pulla** [comment]
I sometimes have this error showing.

`Notice: Array to string conversion in C:\Bitnami\wampstack-7.1.11-0\apache2\htdocs\wp-content\plugins\elementor\includes\css-file\css-file.php on line 364`

Thank you,

**Comment by bainternet** [comment]
@woodswork, @KiQdev, @donwattz1459 

Import Export issue fixed.

@Aljook, @donwattz1459, @nickdgreen
Header, Footer, preview as all are [related to Pro Beta](https://github.com/pojome/elementor/issues/3826 ). please continue this there, no need to re-post, thanks.

@donwattz1459
Yes, background image dynamic is something we will do but not in this version. 

@pulla 
css-file.php did you upgrade from Beta 1 to Beta 3? if so we are sure we fixed it, just to clarify.
as for the `Fatal error: Uncaught Error: Call to a member function get_controls()` please make sure you are running beta 4.

**Comment by pulla** [comment]
@bainternet  Thank you for your quick response. 
Sorry, I thought I was using Beta4.  Yes it fixed in Beta4. Thank you.

But there is 1 more error.
`
Fatal error: Uncaught Error: Call to a member function is_autosave() on boolean in 
C:\Bitnami\wampstack-7.1.11-0\apache2\htdocs\wp-content\plugins\elementor\core\settings\page\manager.php:104 Stack trace: #0 
C:\Bitnami\wampstack-7.1.11-0\apache2\htdocs\wp-content\plugins\elementor\core\settings\manager.php(152): Elementor\Core\Settings\Page\Manager->get_model_for_config() #1 
C:\Bitnami\wampstack-7.1.11-0\apache2\htdocs\wp-content\plugins\elementor\includes\frontend.php(439): Elementor\Core\Settings\Manager::get_settings_frontend_config() #2
C:\Bitnami\wampstack-7.1.11-0\apache2\htdocs\wp-content\plugins\elementor\includes\frontend.php(541): Elementor\Frontend->enqueue_scripts() #3 
C:\Bitnami\wampstack-7.1.11-0\apache2\htdocs\wp-includes\class-wp-hook.php(286): Elementor\Frontend->wp_footer('') #4 
C:\Bitnami\wampstack-7.1.11-0\apache2\htdocs\wp-includes\class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array) #5 
C:\Bitnami\wampstack-7.1.11-0\apache2\htdocs\wp-includes\plugin.php(453): WP_Hook->do_action(Array) #6 
C:\Bit in C:\Bitnami\wampstack-7.1.11-0\apache2\htdocs\wp-content\plugins\elementor\core\settings\page\manager.php on line 104
`

Thank you again.

**Comment by bainternet** [comment]
Thanks everyone, V2 is now live, hurry up and update.

Also, keep testing the [pro](https://github.com/pojome/elementor/issues/3826) and report any bug you find. 


thanks again, we can't do this without your help.

**Comment by SencilloDS** [comment]
It would be great to have dynamic fields in tab widget for the content like you offer in accordeon widget, also I would be happy to have a dynamic field to show post comments with comment form. 
I did such a tab with post content and post comments of my own by creating two elementor templates with theme widgets and using shortcode in tab content in post single site. It works but it´s complicated.
![schnappschuss__002](https://user-images.githubusercontent.com/37189694/37915131-0fec87c0-3119-11e8-9f8a-296bd9b5caf8.png)

**Comment by douglaswcosta** [comment]
Hi, how are you?

I am an enthusiast of Elementor and found a flaw in the mobile menu, when in the categories or shop page, the menu does not open, it is selected and it does not open. Here are some prints to help and also the console errors.

If any information or anything I can help is available, it is my first contact with github and I am not a developer.
![elementor error](https://user-images.githubusercontent.com/38007507/38199979-fe5ab3ba-3668-11e8-84e8-50a68f6bb8ae.png)

**Comment by webk22** [comment]
Can someone help me out I'm getting 500 error when I try to update something using elementor


Debug		

Errors:	
		TypeError: An invalid argument supplied as multiple control value
			at #URL#wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.3.8 - 2:8513
			2019-01-04 13:25 +00:00
			category: InvalidElementData
			tag: Element `undefined` got <> as `pin_image` value. Expected array or object.
			x 2 times

		TypeError: Cannot read property 'currentView' of undefined
			at #URL#wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.3.8 - 2:250893
			2019-01-02 12:55 +00:00

		TypeError: Cannot read property 'html' of undefined
			at #URL#wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.3.5 - 2:220936
			2018-12-27 14:23 +00:00

		TypeError: Cannot read property 'on' of null
			at #URL#wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.3.5 - 2:223730
			2018-12-21 07:42 +00:00

		TypeError: Cannot read property 'style' of undefined
			at #URL#wp-admin/js/editor.min.js?ver=5.0.2 - 1:694
			2018-12-21 07:42 +00:00

		TypeError: Cannot read property 'html' of undefined
			at #URL#wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.3.5 - 2:220936
			2018-12-20 13:27 +00:00
			x 4 times

		ReferenceError: xs_product is not defined
			at #URL#wp-admin/post.php?post=4797&action=elementor&lang=sq - 6:9
			2018-12-20 12:59 +00:00

		TypeError: An invalid argument supplied as multiple control value
			at #URL#wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.3.5 - 2:8513
			2018-12-12 12:56 +00:00
			category: InvalidElementData
			tag: Element `undefined` got <30> as `top_position` value. Expected array or object.

		TypeError: An invalid argument supplied as multiple control value
			at #URL#wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.3.5 - 2:8513
			2018-12-12 12:56 +00:00
			category: InvalidElementData
			tag: Element `undefined` got <20> as `left_position` value. Expected array or object.

		TypeError: Cannot read property 'html' of undefined
			at #URL#wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.3.5 - 2:220936
			2018-12-11 15:24 +00:00

**Comment by Praexor** [comment]
server error (400 bad request)
