### ISSUE TITLE
Pro Rollback function fails

### ISSUE THREAD

**Issue by pingram3541** [pojome/elementor#3905]
Tried to roll back to version - 

Got - Download failed. Unauthorized

even though my unlimited license is in place and shows "status: active" and in system info shows "Library: connected"

I was able to roll back Elementor 2.0 to 1.9.8 but not Pro.

I'd manually roll back pro but can't find where to manually grab older versions of Pro. Logged into my account at Elementor and could find no place to download previous versions.

**Comment by KingYes** [comment]
This is was fixed. Please try again..

**Comment by pingram3541** [comment]
Tried on this and another site.  Both updated Pro to 1.15.5 successfully but still resulting in `Download Failed. Unauthorized` when attempting a rollback to 1.14.2.

I even deactivated the license and reactivated it with my key to ensure it was connected and can see the domain in my list of connected site ay elementor.com

Again...

## I'd manually roll back pro but can't find where to manually grab older versions of Pro. Logged into my account at Elementor and could find no place to download previous versions.

**Comment by KingYes** [comment]
@pingram3541 Fixed too. Thanks.

**Comment by pingram3541** [comment]
Ok thanks I think...I'm not sure what was "fixed too" but I still only see version 1.15.5 as the latest version w/ exception of 2.0 Beta of which I have not tried upgrading to and then rolling back.

Is there a new version I am not seeing?

I am currently trying to roll back from 10.15.5 as I had tried 10.15.4 before but it still fails just as the previous version.

**Comment by carlosnpz** [comment]
I can't roll back my Elementor Pro 2.0.4 to 1.15.6. Unable to create this directory: elementor-pro/modules/assets-manager

**Comment by gmariani** [comment]
Can't rollback from 3.0.1 to 3.0.0. Keeps saying i need to activate it for my domain first... but it was activated to begin with.
