### ISSUE TITLE
Custom CSS - selector - keyword prefix frustration

### ISSUE THREAD

**Issue by pingram3541** [pojome/elementor#4416]
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

Not a deal breaker but quirky and not how one would expect it work.

The custom css feature of using the keyword "selector" in our css is a huge convenience not having to inspect the underlying html to get the unique class assigned to each element's main wrapper, but does it really need a post id class prefixed in front of it?  Can it not just be the unique class of the actual element's main wrapper and we could delegate using a parent when we need it?

## Steps to reproduce

For example, let's say I have a heading H2 with a span tag inside and I want to write custom css to change the font color only for the span within.  Currently there is no way to control this via the Elementor controls so I would:

 -Give my element an id or a class, like .my-heading and write something like this in the custom css area for that element:

`.my-heading h2 span { color: green }`

 -Now, using the "selector" keyword I would write it out like this and not need to give it a unique class or id at all:

`selector h2 span { color: green }`

Which results in something like the following in the actual css:

`.elementor-378 .elementor-element.elementor-element-682dc91e h2 span { color: green }`

The problem is the first part, you see that `.elementor-378` class?  That's waaaay up the DOM chain on an element just inside the body tag which makes any other conditional rules "in between" inaccessible when using the keyword "selector".

For example, it's common to use a sticky class on headers, in my case I want to change an inner heading's span color to red instead of green when the header is sticky.  I'd use something like:

`body:not(.elementor-editor-active) 
#my_header.sticky selector h2 span { color: red }`

Simple right?  The problem is it renders like this making the rule invalid:

```
body:not(.elementor-editor-active) 
#my_header.sticky .elementor-378 .elementor-element.elementor-element-682dc91e h2 span { color: red }
```

This won't work because the `.elementor-378` part is a parent of the `#bs_header.sticky` element and would need to come before it not after it, but using the keyword "selector" I have no way to avoid this and must use the class or id method instead of "selector".

Not a huge deal, it's a simple fix by not using the convenience you provided, but just seems like this would cause more problems than it is solving.  It's like you're intentionally doing this to accommodate people that don't really have a strong understanding of css hierarchy but at the same time frustrating the ones that do and could easily add `.elementor-378` as needed.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

N/A - exists for all

**Comment by pingram3541** [comment]
[Update] - The behavior is already mismatched.

I just discovered that the following rule used in custom css behaves 2 different ways:

`#my_header.sticky selector { ... }`

When in the editor it produces this (as expected):

`#my_header.sticky .elementor-element.elementor-element-5871dca { .. }`

When on the front end (post-378.css compiled file):

`#my_header.sticky .elementor-378 .elementor-element.elementor-element-5871dca`

Which of course is a broken selector because .elementor-378 is not inside of #my_header but rather the other way around.

**Comment by bainternet** [comment]
@pingram3541 

So you are saying that the `selector` token is not working??

**Comment by pingram3541** [comment]
Yes exactly, it's resulting in different behavior, specifically it's output css, live front vs editing front.

On the back end (when editing) it results in targeting the element's wrapper as the highest level delegate in the DOM making the css selector result very easy to work with.

But on the front end, a wrapper DOM element just inside the body tag is prepended to the rule making it a much stronger rule and thus getting in the way of us prefixing DOM elements in front of the token as desired.

**Comment by pingram3541** [comment]
@bainternet Hi Raz, would you prefer I submit an example the fix for this?

**Comment by bainternet** [comment]
@pingram3541 

Please due.

**Comment by pingram3541** [comment]
@bainternet Ok, I did a little bit of digging and even in the latest beta version of Pro, I can see there is differences between the custom css "selector" output between the editor and the front end code.

Since I think the issue lies within Pro I can't easily submit a pull request but I did find a function that exists in the core plugin that mimics the behavior or might actually be the function hook called when rendering the "selector" keyword which might give an idea of how to flush this one out.
![screen shot 2018-07-30 at 11 41 47 am](https://user-images.githubusercontent.com/319284/43416701-df829772-93ed-11e8-81c4-451b94b89ff8.png)

------/core/files/css/post.php-----
![screen shot 2018-07-30 at 11 40 26 am](https://user-images.githubusercontent.com/319284/43416765-0dc6d706-93ee-11e8-9cf6-c791489de2f4.png)

Example custom css:
![screen shot 2018-07-30 at 11 39 05 am](https://user-images.githubusercontent.com/319284/43416789-1e316c0a-93ee-11e8-9e80-03eaef1634b7.png)

Example custom css - output back end editor (note that it is rendered in style tags):

![screen shot 2018-07-30 at 11 39 23 am](https://user-images.githubusercontent.com/319284/43416899-63440ece-93ee-11e8-8099-871f1e282516.png)

Example custom css - front end (note that it is rendered via .css file):

![screen shot 2018-07-30 at 11 40 01 am](https://user-images.githubusercontent.com/319284/43416926-7a9a2266-93ee-11e8-93c1-f96d9ab38d05.png)

Notice how the front end code results in an additional prepended class `.elementor-36` which is a class all the way up the DOM chain residing on the first `.elementor` wrapper div which again means one cannot use parent conditions in between that element and the "selector" target.

![screen shot 2018-07-30 at 11 54 58 am](https://user-images.githubusercontent.com/319284/43417350-9964b58e-93ef-11e8-888a-fd0092ab2a07.png)

**Comment by bainternet** [comment]
@pingram3541 

After revisiting this, this is the desired behavior meaning its like that by design to avoid style from one template overwriting the second one or more, for example, a single page template (1) with a header(2) and a footer(3).
This is also done this way for performance, each with its own unique CSS so once the header CSS is generated it is ready for the next page that uses it and there is no need to regenerate just that part for each page.

as for sticky issues, we already implemented a multiple state sticky with an option to style once sticky is active on at an offset "delay". The docs/guides for that are in the making as we speak.

thanks again.

**Comment by pingram3541** [comment]
@bainternet 

You went from needing feedback to closing the ticket within 4 hours...I'm confused what changed from an open discussion to just forcefully ending the convo?  I apologize if I somehow caused frustration, it was not intended.

Based on your response it would seem that you believe by appending the template's unique parent class in front of the already unique element's class, that this somehow keeps any custom css rules from conflicting with other elements that may also use custom css.  A way to essentially protect inexperienced users from using advanced css rules that may conflict but I'm not sure this would ever happen actually.  I think you are forgetting the element already generates a unique class which is different from ALL other elements on the page.  this is essentially doubling down on what already works while limiting experienced professionals from using the true functionality of the feature.

As far as performance, same principal applies and your reasoning doesn't make sense how it would apply logically.  The element's selector is already unique and likely will be cached via several mechanisms allowing for the same performance across different page visits.

Consider a site-wide header template - that has a Heading element that has the following mark up:

`<span>Call Us Now - </span>(800) 555-1212`

with the following custom css:

```
selector h2 span {
  color: ff0000;
  font-weight: 900;
}
.elementor-sticky--active selector h2 span {
  display: none;
}
```

This custom css would display "Call us Now - (800) 555-1212" with the text before the phone number being the color red with a heavy font weight while the telephone number portion uses the element's inherit styles, (maybe a dark grey color and thinner weight).

Another part of the rule condenses and hides the text when the header's section is "sticky" using the built-in sticky function's class of `.elementor-sticky--active`.

On the back end it renders and works perfectly as expected:

```
.elementor-element.elementor-element-d23a4f7 h2 span {
  color: ff0000;
  font-weight: 900
}
.elementor-sticky--active .elementor-element.elementor-element-d23a4f7 h2 span {
  display: none;
}
```

When scrolled down the page, only the telephone number shows.  When scrolled back up the entire text along with the phone number is revealed along with it's custom styling.

However, **the crux of this topic**....

This same custom css using the `selector` keyword is rendered on the front end as:

```
.elementor-36 .elementor-element.elementor-element-d23a4f7 h2 span {
  color: ff0000;
  text-decoration: underline;
}
.elementor-sticky--active .elementor-36 .elementor-element.elementor-element-d23a4f7 h2 span {
  display: none;
}
```

*where `.element-36` is the header template's post id added as a unique class to the template's parent-most `div` wrapper.  This breaks the intentions of the custom css as the second rule will never apply as the hierarchy is incorrect because `.element-36` is a parent of the element with the `.elementor-sticky--active` rule applied.

It should be:

```
.elementor-36 .elementor-sticky--active .elementor-element.elementor-element-d23a4f7 h2 span {
  display: none;
}
```

But again, this is double duty and not necessary where the following (same as rendered on the back end) is 100% sufficient and still unique:

```
.elementor-sticky--active .elementor-element.elementor-element-d23a4f7 h2 span {
  display: none;
}
```

Additionally adding this unique parent class has no added performance benefit across page loads and only adds restriction to the custom css we can write. 

I really hope you can reconsider this.  If not, it will likely impact the use of Pro's custom css feature w/ the `selector` keyword because it is currently too limiting and unreliable in that it's behavior keeps changing without notice to us and it breaks already working code (as experienced from the back end - currently - and experienced from older sites before this functionality changed).

**Comment by pingram3541** [comment]
@bainternet would love a review of this request again.  This is one of your greatest front end developer features IMO.

The issue is still present, the custom css keyword "selector" behaves completely differently in the back end vs the front end.  The front end adds the post-id waaaay up the DOM chain.

The back end, the keyword "selector" represents the unique widget class of the actual widget we are applying the custom css to.  No parents are involved while still being 100% unique.

The front end, the keyword "selector" adds a page class in front of it which is way up the DOM chain and breaks any css that prefixes the "selector" keyword.

For example, imagine a heading widget's markup is as follows:
```
<div class"elementor-section closed">
...
  <div class="elementor-element elementor-element-bebee4e elementor-widget elementor-widget-heading">
    <div class="elementor-widget-container">
      <h2 class="elementor-heading-title elementor-size-default">My Heading</h2>
    </div>
  </div>
...
</div>
```
Where the parent section is using a custom class of ".closed"

And we're using the keyword "selector" in the heading widget's custom css like so:
```
selector h2 {
  color: red;
}
.closed selector h2 {
  color: #000;
}
```
See how we are using the parent's class to override the color of the heading?
On the back end while in the editor, these rules render as expected:
```
.elementor-element.elementor-element-bebee4e.elementor-widget elementor-widget-heading h2 {
  color: red;
}
.closed .elementor-element.elementor-element-bebee4e.elementor-widget elementor-widget-heading h2 {
  color: #000;
}
```

However, on the front end they render unexpectedly as:
```
.elementor-4490 .elementor-element.elementor-element-bebee4e.elementor-widget elementor-widget-heading h2 {
  color: red;
}
.closed .elementor-4490 .elementor-element.elementor-element-bebee4e.elementor-widget elementor-widget-heading h2 {
  color: #000;
}
```
and the second rule no longer applies because `.elementor-4490` is higher up in the DOM chain than our section with the class of `.closed`.  Here is the markup and why it breaks the css cascade.
```
<div class"elementor-4490">
...
  <div class"elementor-section closed">
  ...
    <div class="elementor-element elementor-element-bebee4e elementor-widget elementor-widget-heading">
      <div class="elementor-widget-container">
        <h2 class="elementor-heading-title elementor-size-default">My Heading</h2>
      </div>
    </div>
    ...
  </div>
...
</div>
```

By having the post-id appended in front it breaks the ability to use a parent item to cascade rules down to the individual elements.  Again, this can be avoided by being more clever with rules or just simply avoiding the use of the convenient "selector" keyword feature.

And again, without pre-pending the post-id, the selector for the widget is still unique and should not ever effect other widgets on the page so I respectfully challenge the necessity to add the post-id on the front end when using the keyword "selector".

I also respectfully challenge how forcing the post-id improves performance somehow.

Ultimately whether the decision is to keep or remove the post-id being prepended to the already unique widget class when using the keyword "selector" in custom css, both the front and back end should at least present a congruent experience as it pertains to the rendered css rules.

**Comment by pingram3541** [comment]
One last suggestion, if we decide to keep the post-id being prepended on the front end due to it being like this for so long and not wanting to possibly break sites using this, maybe we can create a filter or a hook to turn off this behavior on sites that prefer not to have the post-id prepended to rules and would rather prefer the "selector" keyword to only represent the selector of the widget the custom css is being applied to?
