### ISSUE TITLE
JS conflict with Sensei (WooCommerce)

### ISSUE THREAD

**Issue by ludyamano** [pojome/elementor#4752]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
When creating a Header ou Footer template the "Display Conditions" buttons keeps disabled (nothing happens when clicked). This only happens when the Sensei plugin is activated. Some errors are displayed on the Chrome Console.

Screenshot: [https://prnt.sc/juzvw3](url)

Seems to be some kind of JS conflict.

## Steps to reproduce

1. Install Sensei (WooCommerce)
2. Create a new template in Elementor 
3. Click on "Display Conditions" button

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment
Env: https://pastebin.com/D0LrFuLR
<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by ludyamano** [comment]
Any ideas on what is causing the conflict? I have a little technical knowledge but i think i can't solve this myself.

**Comment by bainternet** [comment]
@ludyamano 

Thanks for reporting, we have an Idea, Its caused by Sensei registering his post types at `init` hook with a priority of 100 and our conditions manager currently runs on priority 11.

We are looking for a proper solution and we'll release an update.

**Comment by ludyamano** [comment]
Is there any workaround that can temporarily solve this problem?

**Comment by bainternet** [comment]
@ludyamano 

It should be fixed in 2.1 which is currently in beta #4923 

but if you can't wait simply change the hook in `modules/theme-builder/classes/conditions-manager.php` line 33 which is:
```PHP
add_action( 'init', [ $this, 'register_conditions' ], 11 );
```
to:
```PHP
add_action( 'wp_loaded', [ $this, 'register_conditions' ] );
```

thanks again.

**Comment by srrcampbell** [comment]
Hi I am working with Sensei on Elementor. Once I set my course overview page to the Course Archive Page (screenshot), I consistently get the Preview Cannot be Loaded window (see screenshot). I have gone through all the tips, but still can't edit this page through Elementor. There is no problem loading My Courses page. I believe it must have to do something with the "archive" element as other pages that load through Sensei open in Elementor preview no problem. Please help. I can access the page prior to setting it as my Course Archive Page; however, it needs to be set as an archive page to ensure it is connected to Sensei.
![screen shot 2018-12-14 at 10 19 26 am](https://user-images.githubusercontent.com/45952987/50120488-eec3ff80-0212-11e9-835b-3296f36267b9.png)
![screen shot 2018-12-14 at 10 19 26 am](https://user-images.githubusercontent.com/45952987/50120491-f1265980-0212-11e9-9898-c0a10a5f7755.png)
