### ISSUE TITLE
Elementor "Scrolling Effect: Sticky" Causes Auto Scrolling Like a Ghost

### ISSUE THREAD

**Issue by smile00000** [pojome/elementor#5123]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description

With the new "Elementor Scrolling Effect: Sticky" feature turned on for the header, Elementor is making all of our pages autoscroll like a ghost.

https://bit.ly/2zLavSW

## Steps to reproduce
Add header template to page
Click section
Click Layout
Select Full width
Select Height: Default or Min height (neither fix this)
Click advanced
Click scrolling effect
Sticky: Yes

Now go view the website and you will see it's autoscrolling like a ghost. :O 

First we tried it with Height: Default
https://www.useloom.com/share/1fbaadd026b04e54b279f13f1087b6d8

Then we tried it with Height: Min Height like Elementor support email suggested and it didn't help. They had no workaround at this point:
https://www.useloom.com/share/bd8aa2c411b7449cbdfe798a489efa95

## Isolating the problem
- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.
No matter what we do, with sticky header on, it autoscrolls our pages.

## Environment

Current version of Wordpress
Current version of Elementor & Elementor Pro 
Current version of Woo Commerce Storefront Theme

**Comment by bainternet** [comment]
@smile00000 

Can you make a  screen capture? also can you paste your system info?

**Comment by smile00000** [comment]
1. Sceen Capture:
What do you mean screen capture? I just did two screen captures above in Loom that reflect it?

2. Browser:
Google Chrome
I don't see it in safari and I don't have firefox, but ask Andri Support Tech of Elementor as he said this is a known issue with Elementor.

3. System Info:
				
== Server Environment ==
	Operating System: Linux
	Software: Flywheel/4.1.0
	MySQL version: 5.6.32
	PHP Version: 7.1.18-1+ubuntu16.04.1+deb.sury.org+1
	PHP Max Input Vars: 4000
	PHP Max Post Size: 300M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.9.7
	Site URL: https://themoodmachine.com
	Home URL: https://themoodmachine.com
	WP Multisite: No
	Max Upload Size: 300 MB
	Memory limit: 768M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Storefront
	Version: 2.3.2
	Author: Automattic
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 2.1.3
		Author: Elementor.com

	Elementor Pro
		Version: 2.0.16
		Author: Elementor.com

	GPL Kit
		Version: 2.0.0
		Author: GPL Kit

	MailChimp for WooCommerce
		Version: 2.1.9
		Author: MailChimp

	Responsive Menu Pro
		Version: 3.1.14
		Author: Peter Featherstone

	Safe SVG
		Version: 1.6.1
		Author: Daryll Doyle

	Storefront Powerpack
		Version: 1.4.9
		Author: WooCommerce

	Tidio Chat
		Version: 3.3.0
		Author: Tidio Ltd.

	WooCommerce
		Version: 3.4.3
		Author: Automattic

	WooCommerce Bookings
		Version: 1.11.2
		Author: Automattic

	WooCommerce Frontend Manager
		Version: 4.2.0
		Author: WC Lovers

	WooCommerce Frontend Manager - Analytics
		Version: 1.2.1
		Author: WC Lovers

	WooCommerce Frontend Manager - Groups & Staffs
		Version: 2.1.0
		Author: WC Lovers

	WooCommerce Frontend Manager - Product Hub
		Version: 1.0.1
		Author: WC Lovers

	WooCommerce Frontend Manager - Ultimate
		Version: 4.2.0
		Author: WC Lovers

	WooCommerce Google Analytics Pro
		Version: 1.5.1
		Author: SkyVerge

	WooCommerce Multivendor Membership
		Version: 2.1.0
		Author: WC Lovers

	WooCommerce PayPal Checkout Gateway
		Version: 1.6.1
		Author: WooCommerce

	WooCommerce Product Vendors
		Version: 2.1.6
		Author: WooCommerce

	WooCommerce Services
		Version: 1.15.1
		Author: Automattic

	WooCommerce Stripe Gateway
		Version: 4.1.7
		Author: WooCommerce

	WooCommerce Subscriptions
		Version: 2.3.2
		Author: Prospress Inc.

	WP Job Manager
		Version: 1.31.2
		Author: Automattic

	WP Job Manager - Resume Manager
		Version: 1.16.1
		Author: Automattic

	Yoast SEO: WooCommerce
		Version: 7.8
		Author: Team Yoast

	Yoast SEO Premium
		Version: 7.8.1
		Author: Team Yoast


== Debug ==
	Errors: 
		ReferenceError: Skype is not defined
			at https://themoodmachine.com/wp-admin/post.php?post=1342&action=elementor - 2:2
			2018-07-18 12:52 +00:00
			x 2 times

		ReferenceError: Skype is not defined
			at https://themoodmachine.com/wp-admin/post.php?post=1118&action=elementor - 2:2
			2018-07-17 17:55 +00:00

		ReferenceError: Skype is not defined
			at https://themoodmachine.com/wp-admin/post.php?post=1102&action=elementor - 2:2
			2018-07-17 17:54 +00:00

		ReferenceError: Skype is not defined
			at https://themoodmachine.com/wp-admin/post.php?post=1118&action=elementor - 2:2
			2018-07-17 17:28 +00:00

		ReferenceError: Skype is not defined
			at https://themoodmachine.com/wp-admin/post.php?post=1342&action=elementor - 2:2
			2018-07-17 17:28 +00:00

		TypeError: Cannot read property 'get' of undefined
			at https://themoodmachine.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.1.3 - 2:124021
			2018-07-17 13:02 +00:00

		TypeError: Cannot read property 'pageYOffset' of undefined
			at https://themoodmachine.com/wp-includes/js/jquery/jquery.js?ver=1.12.4 - 4:30811
			2018-07-17 13:00 +00:00

		ReferenceError: Skype is not defined
			at https://themoodmachine.com/wp-admin/post.php?post=1342&action=elementor - 2:2
			2018-07-17 12:25 +00:00
			x 7 times

		TypeError: Cannot read property 'updateMap' of undefined
			at https://themoodmachine.com/wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=2.0.16 - 2:23324
			2018-07-16 21:27 +00:00

		ReferenceError: Skype is not defined
			at https://themoodmachine.com/wp-admin/post.php?post=1118&action=elementor - 2:2
			2018-07-16 21:16 +00:00
			x 2 times

**Comment by TLJ86** [comment]
Hi guys, I have the same issue. It happens on Chrome on my Chromebook and Chrome for Android. It happens intermittently on Chrome for windows.

Here's my example: https://vip-booth.dyfiwebservices.co.uk/michelle-dans-wedding/

The ghost scrolling happens when you go below the full size hero image, it then scrolls the page up until it reaches the bottom of the hero section/top of the content section.

**Comment by bainternet** [comment]
@smile00000 @TLJ86 

This should be fixed in Elementor Pro 2.1 which is now in Beta #4923 

thanks

**Comment by smile00000** [comment]
Wonderful ok thanks! Is it coming out July 23rd still?

**Comment by willdante** [comment]
Hello,

Same issue for me, still here with Elementor 2.1.6 :(
Any news about this bug ?

Thanks in advance.

**Comment by webinsightin** [comment]
The issue still haven't been resolved yet and Its very frustrating. Kindly reply ASAP

**Comment by willdante** [comment]
I confirm, the issue is still here 😭

Le ven. 31 août 2018 à 09:39, webinsightin <notifications@github.com> a
écrit :

**Comment by galib033** [comment]
issue still here

**Comment by creationvilla** [comment]
Just solving the problem by decreasing "Inner Section width" 1000 to 950(in my case) of the Master section , where the ghost scroll happens.
Advise you guys to try to manipulate the value for the respective section width, hope it'll help you guys.

**Comment by 66redBastard** [comment]
issue still here
