### ISSUE TITLE
wp query from dynamic content option

### ISSUE THREAD

**Issue by unclerom** [pojome/elementor#5238]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Creating any layout using dynamic content. using posts query as backgrounds etc
**Describe the solution you'd like**
When selecting the dynamic content option inside of editor add the option for wp query. Giving the ability to query a post type outside of the current post.

**Comment by bainternet** [comment]
@unclerom 


Can you explain better?

**Comment by unclerom** [comment]
Adding wp query on dynamic controls giving you the ability to essentially use any widget with dynamic controls as a post widget. 
**For example:**
I did this with the portfolio widget https://snag.gy/nYuLS6.jpg by using 1 widget for each post and each offsetting by +1 but cant show titles (no good for mobile) and limited customizability. 
With query in dynamic controls we could take a column,  query in posts featured image for column background, then in this column a title widget querying same post title, text widget querying same post excerpt/content, and a button querying read more, now you have a posts widget with more options than the current posts/portfolio widgets. This and any other layout of displaying latest posts is possible with query option in dynamic controls.
 **Example 2:** Take a custom post type, courses for example, query in latest course featured image, title, and excerpt into CTA widget now you have a featured/latest course widget with all the features the elementor cta widget has.
*These are just static , but a nice feature if you want a custom designed way to display your latest 3 or 4 posts/custom posts.*
 To really make it perfect would be to then repeat or loop that column with dynamic widgets inside pulling in query data..But nothing's perfect

**Comment by black-eye** [comment]
+1

**Comment by bentalgad** [comment]
+1 Amazing Idea!!!

**Comment by bainternet** [comment]
I merged this issue with  #4440, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Comment by bentalgad** [comment]
It's funny that you have for dynamic content in every field separately instead of just having the option to add dynamic fields any where just like in beaver builder which lets you add it even inside text and even multiple dynamic content's in one field. a lot of posts on how to do fancy effects but basic features are still missing from the beginning of this plugin.
