### ISSUE TITLE
[Bug] Video Widget | Image Overlay without Lightbox

### ISSUE THREAD

**Issue by stevek28** [pojome/elementor#6015]
Hi, 
I guess there is a little bug with the video widget. When you use an image overlay for a video, and do not select Lightbox, the video won't start to play directly when you click on the (EM overlay) play icon.

You have to start it manually by pressing the Youtube Play button to start it.
No matter if autoplay is enabled or not.

When you use the video Lightbox feature together with image overlay - it is working fine and starts directly!

[https://www.useloom.com/share/f9f201ee7a484c538c158485b3050bae](https://www.useloom.com/share/f9f201ee7a484c538c158485b3050bae)

Thank you! 

Greetings,

stefan

Elementor / Pro latest versions
Wordpress 4.9.8
Tested on Twenty Seventeen default theme / no other plugins installed..

**Comment by bainternet** [comment]
@stevek28 

We have just tested it and we can't seem to replicate the issue,

Please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

thanks.

**Comment by stevek28** [comment]
@bainternet , please try on chrome.. latest Version 70.0.3538.77 (Offizieller Build) (64-Bit) or 69.xxx
It works fine on firefox!

thx!

**Comment by stevek28** [comment]
I sent it to support...

**Comment by rogerd202** [comment]
Any update on this issue as I'm finding the same thing. Works on FF but not Chrome or Edge..........?

**Comment by kroeberk** [comment]
Yup, Autoplay does not work for me on Chrome with the lightbox.

**Comment by danygit** [comment]
I have the same problem.

**Comment by danygit** [comment]
@stevek28 this bug was resolved for you ?

**Comment by danstramer** [comment]
Hi, any updates on this?
Thanks

**Comment by rogerd202** [comment]
It's started working for me after some updates so it now seems correct. Using WP 5.1.1, Elementor 2.5.15 and Events Calendar 4.9.2

**Comment by danstramer** [comment]
I have installed Elementor 2.5.15, Pro 2.5.8
See demo here:
https://www.dropbox.com/s/7iyqf5lmmqo6b1t/elementor-video.avi?dl=0

**Comment by iangioffre** [comment]
It's been years now... Still getting this bug on Chrome. Works fine on Edge. Any fixes yet?

WP 5.4.2
Elementor 2.9.11

**Comment by Cheekypixel** [comment]
Any update on this? I am also having this issue unless you select lightbox it will not work on Chrome or Firefox.

**Comment by bryan042092** [comment]
Any updates on this? 

Video with Overlay and not using light box - still not working after clicking play on Chrome Browser Version 86.0.4240.198

Wordpress  5.5.3
Elementor Version 3.0.13
Elementor Pro Version 3.0.6

**Comment by stevek28** [comment]
On Nov, 1 2018 I received the following answer from EM support concerning this issue.. 

+++++++++++

Hi Stefan,

Thank you for contacting us.

This is due to the autoplay policy of Google in their Chrome browser:
https://developers.google.com/web/updates/2017/09/autoplay-policy-changes

To allow your video to play automatically in Chrome, simply enable the 'Mute' option.

![chrome-mute](https://user-images.githubusercontent.com/8449694/100391584-31fc8f00-3034-11eb-9f7f-bf992175b4ce.png)

+++++++++++++

Haven't used EM for I while and cannot remember if it fixed it.. Can anyone please check if the Mute setting mentioned by EM support makes any difference?

Thank you!

Stefan
