### ISSUE TITLE
WooCommerce + Elementor Variable Product Image

### ISSUE THREAD

**Issue by zimpstar** [pojome/elementor#7038]
Hi.

I have a rather peculiar problem that I have been trying to fix for a few days now, but I've had no luck in solving it.

I'm running WooCommerce with Elementor Pro on the Elementor Hello Theme (their own lightweight theme) for a webshop selling variable products.

To the main issue:

When using the "Elementor canvas" page layout, the variable product pictures simple stop working. Whatever combination I try on the dropdown to the right ("Färg på glas") + ("Färg på ram) the image stays the same. They are supposed to change based on the color combination.

When not using the elementor canvas (standard layout) it's working just fine - so I'm confident it's not a theme issue. Besides, I've tried Storefront, Generatepress and native WP themes but I still encounter the same issue.

I suspect there is some conflict in the PHP but I'm terrible at it. I would consider myself rather affluence in CSS but no tricks like playing with opacity, position:absolute and so on has yielded any results.

Feel free to see it yourself in action here: http://178.128.203.246/produkt/spegel-ego-standard/

Interesting to note is that the pictures do change during the checkout process, just not in the main product page view.

Any ideas on how to solve the matter?

Attached my System-I
[system-info-178.128.203.246-11-02-2019.txt](https://github.com/pojome/elementor/files/2852014/system-info-178.128.203.246-11-02-2019.txt)
nfo

**Comment by zimpstar** [comment]
**Update**:

I reproduced this bug on an additional page and below you'll find two links, the first is using the 'default' layout and the second is using the 'elementor canvas layout (with the product images + add to cart widgets). You'll find that in the first instance the images are changing just fine when you play around with variants.

https://zimp.se/product/poster-1-working [this one changes images]
https://zimp.se/product/poster-1/ [this one is not]

**Comment by zimpstar** [comment]
[shilo-ey](/shilo-ey)

**Comment by zimpstar** [comment]
Could this be a hook problem?

**Comment by soyket** [comment]
you are trying to edit products directly with elementor probably which is why you face the issue. You need to use the theme builder to edit the Single product.

**Comment by gluleci** [comment]
same problem, i want to change image when click color variations.

https://www.vitello.com.tr/urun/montana-sandalye/

**Comment by keloco7** [comment]
Same problem, also I saw a video on youtube of a guy having the same issue

**Comment by sosaheri** [comment]
me too

in my case if I use Image widget and set dynamic data from product desn't work
but
if a use Product Image widget I don't have problem but lose other features

**Comment by sosaheri** [comment]
> same problem, i want to change image when click color variations.
> 
> https://www.vitello.com.tr/urun/montana-sandalye/

how do you fix the problem?

**Comment by Alfred4444** [comment]
**The same problem. It's frustrating.** You have the option to create a dynamic element so that the product image appears in a product or background widget as a header. but then the image does not change in the variable products. I consider it a serious failure. I place my trust in the Elementor team and expect a result to this problem, I have seen many people happening to it. **I think they should give us an answer to the problem now.**

**Comment by Yahlena** [comment]
Same problem. Using Theme Builder and product image will not change.

**Comment by BaldoTuttle** [comment]
Same problem. With the Single Product Template images have been changed but as I want to create very individual product pages, I could not use the Single Product Template. And editing the product page in Elementor, the Elementor Full Width Template is the only choice.
But then the product image/variation connection is broken.
As this post began in Februar 2019, is there a chance this would be fixed?

**Comment by royce75** [comment]
No news on this? I know that this is still an issue, but can it be that hard to see "some kind" of an solution?

**Comment by Pardaigle** [comment]
I have the same problem with storefront theme, this is very annoying.

**Comment by soyket** [comment]
> I have the same problem with storefront theme, this is very annoying.

you are trying to edit products directly with elementor probably which is why you face the issue. You need to use the theme builder to edit the Single product.

**Comment by soyket** [comment]
> No news on this? I know that this is still an issue, but can it be that hard to see "some kind" of an solution?

you are trying to edit products directly with elementor probably which is why you face the issue. You need to use the theme builder to edit the Single product.

**Comment by Pardaigle** [comment]
> > No news on this? I know that this is still an issue, but can it be that hard to see "some kind" of an solution?
> 
> you are trying to edit products directly with elementor probably which is why you face the issue. You need to use the theme builder to edit the Single product.

No, I use elementor theme builder with WooCommerce product images widget.

**Comment by soyket** [comment]
Well, if that's the case, you should not use caves template there, it
should be elementor full width template at most, since canvas will try to
remove all script from the template.

**Comment by lioncatde** [comment]
+1 on this issue, any news or workarounds?

**Comment by denihub** [comment]
> same problem, i want to change image when click color variations.
> 
> https://www.vitello.com.tr/urun/montana-sandalye/

How did you resolve the issue? I see that the colour of your products change.

**Comment by Triskal** [comment]
Here's how you can try to debug:

1. Add this to your wp-config.php: `define( 'SCRIPT_DEBUG', true );`
2. Open wp-content/plugins/woocommerce/assets/js/frontend/add-to-cart-variation.js
3. Find this line: `$.fn.wc_variations_image_update = function( variation ) {`;
4. Add this to the next line: `console.log(variation);`
5. Reload page, hit F12 and watch activity in console while selecting variations.

If you see JavaScript activity, you have all scripts loaded and WooCommerce is functioning properly and your issue is most likely this: When you select a variation, WooCommerce's frontend script traverses to the closest parent element with the CSS class `product`. If it finds one, it tries to find a descendant element which has the CSS class `images`. If it can't find either, variation images will not change. You can run into this problem if you have Woocommerce widgets that are outside of the normal "body", eg. ie. in the header.

**Comment by zimpstar** [comment]
Update for anyone wondering:

Using canvas pretty much screws up the js running, so any functionability will destroy if you use the canvas layout.

**The fix is simple**: use the theme builder to build your product page and you won't encounter this issue.

**Comment by reachdigitalaus** [comment]
@zimpstar I am now facing this issue, I have built it using the themebuilder for my single product. For me is on desktop works fine but mobile the image will not change. Any ideas?

**Comment by okkine** [comment]
Any update on this? I recently upgraded to Elementor Pro, and it's not very encouraging to see that this problem was reported nearly TWO YEARS AGO, and it still has not been addressed.

In my case, the thumbnail updates, but the large image does not change. Everything works fine on desktop.

For the record: No, I am NOT trying to edit the products directly. I am using the theme builder to edit the single product template, which is then applied automatically to all products in the shop.

**Comment by gsimeone** [comment]
For anyone who is wondering how to solve: 
Building product page with Elementor theme builder seems not adding the class "single-product-variation" on the main div that contains product data.

So, If the theme is looking for nested elements with "single-product-variation" to find the image gallery to refresh, it will not work.

To solve, add the class where is missing by the code or simply by Elementor Editor, and it will works.

**Comment by dor-p** [comment]
@gsimeone Hi there, Can you please elaborate about your solution?
Would really help me if you can describe how you solved it with descriptive details.
Thank you!

**Comment by Fishionboy** [comment]
I solved by clearing the WordPress cache with a random plugin for that.

At the beginning it didn't change but it does.

**Comment by Demonpersi** [comment]
Looking for a way to solve this and there is none that really helped,did someone find the solution?

**Comment by dor-p** [comment]
@Demonpersi  Hi , I managed to solve it by duplicating the existing elementor template of the product page. After duplicating I just used the new one and deleted the old one. Weird as hell, but worked for me. Clear the cache in between.

Best of luck

**Comment by ApiceSviluppo** [comment]
has anyone solved it?

**Comment by rysimps** [comment]
This is still happening as of 17/02 - latest updates with Elementor Pro - Full width template and Woocommerce. Has anyone worked out a resolution? You have to set up the template through theme builder to add the necessary conditions for Woocommerce.

**Comment by rysimps** [comment]
I have a fairly simple workaround for the time being - the image being generated is a dynamic PRODUCT IMAGE. Remove the background image from this element and instead put PRODUCT IMAGE into the column. That works.

**Comment by Triskal** [comment]
Okay, everybody. **This is not a bug.** Elementor can not fix this and has not reason to involve itself in trying to do so. This does not concern them. This occurs simply because for some reason the final HTML is missing something that is necessary for the JavaScript to work. It is not Elementor's fault, so it is not their job to fix it. Please consult the following:

![elementor-bug](https://user-images.githubusercontent.com/4559903/154418262-ec6cd929-ebd6-4db4-b0b8-45f0f83857e9.gif)

In the above case the product variation selector **has no parent element** that has the class _product_, which is required. This is because I have split up the conventional Woocommerce layout and designed the page differently. Therefore the image does not change. But see what happens when I add the _product_ class to a parent element of the product variation selector. The issue is fixed instantly. The way you can confirm if this is the case is by doing a CSS selector search in F12 Inspector and going through the results:

![image](https://user-images.githubusercontent.com/4559903/154420319-8b02ab86-ad60-4c55-8a58-8917c8da82d3.png)

Most likely you will find an element with the class _product_ but the product variation selector is outside of it, or you will not find an element with the _product_ class at all.

**Comment by thyklaus** [comment]
I still have a hard time understanding how to solve this "Image Variations Functionality". Isn't there someone who can explain it, in another way or with a video?

**Comment by mikeleigh30** [comment]
> Okay, everybody. **This is not a bug.** Elementor can not fix this and has no reason to involve itself in trying to do so. This does not concern them. This occurs simply because for some reason the final HTML is missing something that is necessary for the JavaScript to work. It is not Elementor's fault, so it is not their job to fix it. Please consult the following:
> 
> ![elementor-bug](https://user-images.githubusercontent.com/4559903/154418262-ec6cd929-ebd6-4db4-b0b8-45f0f83857e9.gif) [ ![elementor-bug](https://user-images.githubusercontent.com/4559903/154418262-ec6cd929-ebd6-4db4-b0b8-45f0f83857e9.gif) ](https://user-images.githubusercontent.com/4559903/154418262-ec6cd929-ebd6-4db4-b0b8-45f0f83857e9.gif) [ ](https://user-images.githubusercontent.com/4559903/154418262-ec6cd929-ebd6-4db4-b0b8-45f0f83857e9.gif)
> 
> In the above case the product variation selector **has no parent element** that has the class `product`, which is required. This is because I have split up the conventional Woocommerce layout and designed the page differently. Therefore the image does not change. But see what happens when I add the `product `class to a parent element of the product variation selector. The issue is fixed instantly. The way you can confirm if this is the case is by doing a CSS selector search in F12 Inspector and going through the results:
> 
> ![image](https://user-images.githubusercontent.com/4559903/154420319-8b02ab86-ad60-4c55-8a58-8917c8da82d3.png)
> 
> Most likely you will find an element with the class `product` but the product variation selector is outside of it, or you will not find an element with the `product` class at all.
> 
> Here's how my product page template is structured. As you can see, I have a separate template for the cart, product images etc.: ![image](https://user-images.githubusercontent.com/4559903/154422349-b0badd7e-8d97-4c62-b48b-ebdbb1977038.png)
> 
> So where does the `product` class need to go? In my case here: ![image](https://user-images.githubusercontent.com/4559903/154422707-c1e8ac52-39be-4cf0-b044-f3aa3cfaa2a0.png)
> 
> Please understand that this is in no way a universal cookie cutter solution and it is always a possibility that your problem is caused by something entirely different. This is essentially the same answer I have already given above, just more verbose and with more pictures.

100% correct here.  Great post.
